### ISSUE TITLE
when i add client or formyself this happends

### ISSUE THREAD

**Issue by mut3-sux** [angristan/wireguard-install#100]
Job for wg-quick@wg0.service failed because the control process exited with error code. See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.

**Comment by robiiinos** [comment]
Which OS did you use?

**Comment by mut3-sux** [comment]
ubuntu 16

**Comment by angristan** [comment]
Make sure the machine is up-to-date (specifically the kernel, you need to reboot after a kernel update) before installing wireguard. Otherwise the DKMS module won't build.
