### ISSUE TITLE
I am getting this error

### ISSUE THREAD

**Issue by xenstar** [angristan/wireguard-install#110]
After I setup the wireguard code on digital ocean droplet, I am getting this error

Job for wg-quick@wg0.service failed because the control process exited with error code.
See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.

How to fix it?

**Comment by randomshell** [comment]
I guess you didn't see `systemctl status wg-quick@wg0.service` for details? Run it and paste here the relevant lines please. Also, what OS did you use?

**Comment by anhnt** [comment]
Run this:
```
apt-get install wireguard-dkms wireguard-tools linux-headers-$(uname -r)
```

Source: https://stackoverflow.com/a/54836833/1953850
