### ISSUE TITLE
error at the end

### ISSUE THREAD

**Issue by mmpma** [angristan/wireguard-install#111]
when installation finished , show this error

> Job for wg-quick@wg0.service failed because the control process exited with error code.
> See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.
 
and when i ran systemctl status wg-quick@wg0.service , the result was :

> ● wg-quick@wg0.service - WireGuard via wg-quick(8) for wg0
>    Loaded: loaded (/lib/systemd/system/wg-quick@.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Mon 2020-08-03 16:46:53 EDT; 2min 57s ago
>      Docs: man:wg-quick(8)
>            man:wg(8)
>            https://www.wireguard.com/
>            https://www.wireguard.com/quickstart/
>            https://git.zx2c4.com/wireguard-tools/about/src/man/wg-quick.8
>            https://git.zx2c4.com/wireguard-tools/about/src/man/wg.8
>   Process: 7965 ExecStart=/usr/bin/wg-quick up wg0 (code=exited, status=1/FAILURE)
>  Main PID: 7965 (code=exited, status=1/FAILURE)
> 
> Aug 03 16:46:53 azbb systemd[1]: Starting WireGuard via wg-quick(8) for wg0...
> Aug 03 16:46:53 azbb wg-quick[7965]: [#] ip link add wg0 type wireguard
> Aug 03 16:46:53 azbb wg-quick[7965]: RTNETLINK answers: Operation not supported
> Aug 03 16:46:53 azbb wg-quick[7965]: Unable to access interface: Protocol not supported
> Aug 03 16:46:53 azbb wg-quick[7965]: [#] ip link delete dev wg0
> Aug 03 16:46:53 azbb wg-quick[7965]: Cannot find device "wg0"
> Aug 03 16:46:53 azbb systemd[1]: wg-quick@wg0.service: Main process exited, code=exited, status=1/FAILURE
> Aug 03 16:46:53 azbb systemd[1]: wg-quick@wg0.service: Failed with result 'exit-code'.
> Aug 03 16:46:53 azbb systemd[1]: Failed to start WireGuard via wg-quick(8) for wg0.

plz help me

**Comment by randomshell** [comment]
https://github.com/angristan/wireguard-install/blob/2848ceefa5d31b1fc99e854025594f83c917460d/wireguard-install.sh#L203

There is a message saying to reboot at the end of the installation. Please do that.

**Comment by nibty** [comment]
I received the same error on Centos 8 on AWS. A reboot did not fix the issue. 

I'm using a new official AMI https://wiki.centos.org/Cloud/AWS

**Comment by navilg** [comment]
Thanks @nibty . Able to replicate the issue and resolution. Seems like issue is with kernel type (Standard and non-standard). Check below link. I will create a pull request after adding above packages in installation step.

https://www.wireguard.com/install/#centos-8-module-kmod-module-dkms-tools

**Comment by mmpma** [comment]
reboot fixed my problem
tanks a lot

> https://github.com/angristan/wireguard-install/blob/2848ceefa5d31b1fc99e854025594f83c917460d/wireguard-install.sh#L203
> 
> There is a message saying to reboot at the end of the installation. Please do that.

**Comment by navilg** [comment]
In my test, reboot didn't help.

Steps to replicate:

- Create new instance of CentOS 8
- Run the script. 
- Check the service wg-quick@wg0.service
- If it shows failed. Reboot the instance. And try to start the service.
- If it still don't start, install elrepo-release and kmod-wireguard.
- Start the service.

**Comment by angristan** [comment]
Same here, working fine on CentOS 7 and 8.
