### ISSUE TITLE
Add the possibility to use a pre-shared symmetric key

### ISSUE THREAD

**Issue by LiveChief** [angristan/wireguard-install#12]
Add the possibility to set pre shared keys

**Comment by LiveChief** [comment]
https://github.com/angristan/wireguard-install/pull/13

**Comment by angristan** [comment]
From the WireGuard technical white paper:

> In order to mitigate any future advances in quantum computing, WireGuard also supports a mode in which any pair of peers might additionally pre-share a single 256-bit symmetric encryption key between themselves, in order to add an additional layer of symmetric encryption. The attack model here is that adversaries may be recording encrypted traffic on a long term basis, in hopes of someday being able to break Curve25519 and decrypt past traffic. While pre-sharing symmetric encryption keys is usually troublesome from a key management perspective and might be more likely stolen, the idea is that by the time quantum computing advances to break Curve25519, this pre-shared symmetric key has been long forgotten. And, more importantly, in the shorter term, if the pre-shared symmetric key is compromised, the Curve25519 keys still provide more than sufficient protection. In lieu of using a completely post-quantum crypto system, which as of writing are not practical for use here, this optional hybrid approach of a pre-shared symmetric key to complement the elliptic curve cryptography provides a sound and acceptable trade-off for the extremely paranoid. Furthermore, it allows for building on top of WireGuard sophisticated key-rotation schemes, in order to achieve varying types of post-compromise security.

https://www.wireguard.com/papers/wireguard.pdf (5.2)

**Comment by LiveChief** [comment]
> From the WireGuard technical white paper:
> 
> > In order to mitigate any future advances in quantum computing, WireGuard also supports a mode in which any pair of peers might additionally pre-share a single 256-bit symmetric encryption key between themselves, in order to add an additional layer of symmetric encryption. The attack model here is that adversaries may be recording encrypted traffic on a long term basis, in hopes of someday being able to break Curve25519 and decrypt past traffic. While pre-sharing symmetric encryption keys is usually troublesome from a key management perspective and might be more likely stolen, the idea is that by the time quantum computing advances to break Curve25519, this pre-shared symmetric key has been long forgotten. And, more importantly, in the shorter term, if the pre-shared symmetric key is compromised, the Curve25519 keys still provide more than sufficient protection. In lieu of using a completely post-quantum crypto system, which as of writing are not practical for use here, this optional hybrid approach of a pre-shared symmetric key to complement the elliptic curve cryptography provides a sound and acceptable trade-off for the extremely paranoid. Furthermore, it allows for building on top of WireGuard sophisticated key-rotation schemes, in order to achieve varying types of post-compromise security.
> 
> https://www.wireguard.com/papers/wireguard.pdf (5.2)

i wanna die.

**Comment by LiveChief** [comment]
https://pics.me.me/roses-are-red-this-life-isa-existence-spain-i-just-15266613.png

**Comment by LiveChief** [comment]
![roses-are-red-this-life-isa-existence-spain-i-just-15266613](https://user-images.githubusercontent.com/16564273/58202256-019c9d80-7ca5-11e9-955c-32f518ed2810.png)

**Comment by Leopere** [comment]
I dislike that they refer to it as the "extremely paranoid" as much as the privacy-conscious at this point you are currently losing freedoms for things you say and do online people should be conscious of these things.  Saying anything on social media is one of those things that people forget that are never forgotten let alone your browsing habits.  I wonder what the dictators would be and current would say once options like WireGuard become part of the base specification of the internet infrastructure.
