### ISSUE TITLE
RTNETLINK: permission denied

### ISSUE THREAD

**Issue by TheMcSebi** [angristan/wireguard-install#124]
It might be valuable to add the following line to /etc/sysctl.d/wg.conf:

net.ipv6.conf.all.disable_ipv6 = 0

I used this script on a Debian 10 VPS from Contabo.de. For some reason it had this parameter set, which prevented the wireguard interface from booting up, throwing the error message in the issue title.

This link helped me resolve this issue:
https://ask.openstack.org/en/question/68190/how-do-i-resolve-rtnetlink-permission-denied-error-encountered-while-running-stacksh/

**Comment by randomshell** [comment]
> `net.ipv6.conf.all.disable_ipv6 = 0`

We can't enable IPv6 by default for all users, some have reasons to disable it.

It isn't this script job to fix a not working IPv6 configuration as it affects all the system and the apps. We can only change the check to make sure the system can successfully reach an IPv6 only host.
