### ISSUE TITLE
Remove confirmation steps during install

### ISSUE THREAD

**Issue by angristan** [angristan/wireguard-install#15]
`apt-get -y` etc

**Comment by LiveChief** [comment]
it could have taken 2 sec to add it to the script rather than creating this.

why was this created?
for documentation purposes???

**Comment by angristan** [comment]
I did not have the time to do it so I created an issue in order to fix this properly. Otherwise this is how you get a buggy software.

**Comment by LiveChief** [comment]
This way it will take a Month to write a script

**Comment by liberodark** [comment]
https://github.com/angristan/wireguard-install/pull/46

**Comment by angristan** [comment]
Fixed by https://github.com/angristan/wireguard-install/commit/b9da4d03cdac26430737ed1cbaed37bfb66e8c9f
