### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by TheDevFab** [angristan/wireguard-install#150]
Hi,

I was wondering if the WireGuard client keeps any logs on my VPS and if I can further harden? Optimally Id like to keep no logs at all / logs being removed at the same time as they are being created.

**Comment by randomshell** [comment]
From what I know the logs are from the systemd service and don't include any client or other sensitive information. There isn't a file for logs like with OpenVPN that keeps track of users and connections.

> I can further harden

It depends what you want to harden. You could limit where the clients can connect from by editing the `AllowedIPs` option in your server config but ultimately you should keep your profiles in a safe place. Someone else having your profile might not be able to connect if you do the above but could decrypt your traffic.

**Comment by TheDevFab** [comment]
Awesome, thanks for the information. Apprentice it.
