### ISSUE TITLE
Issue when there is no ipv6

### ISSUE THREAD

**Issue by shirshak55** [angristan/wireguard-install#151]
I think we should check if ipv6 is enabled or not. Most of the company i work disable ipv6 because of various issues. 

There is issue because it uses ipv6 table commands?
And it also uses ipv6 in wiregaurd.

In openvpn setup i think there was option of ipv6 though?

**Comment by randomshell** [comment]
> There is issue because it uses ipv6 table commands?
> And it also uses ipv6 in wiregaurd.

The IPv6 address are internal to the VPN subnet, I don't see why would they cause an issue to the tunnel which is IPv4 if you configured an IPv4 endpoint. Have you tried and got a specific error or couldn't connect?

**Comment by shirshak55** [comment]
I exactly forgot the error but  it would say something like `RTNETLINK answers: File exists`. I had disabled ipv6 from grub and sysctl  for my own reason.

**Comment by MinhThienDX** [comment]
@shirshak55 IPv4 only config is here https://github.com/MinhThienDX/wireguard-install/blob/ipv4/wireguard-install-ipv4.sh

**Comment by shirshak55** [comment]
@MinhThienDX thanks

**Comment by MinhThienDX** [comment]
@shirshak55 I guess this issue is resolved, would you kindly close it?
