### ISSUE TITLE
Endpoint uses local IP address (should use public IP)

### ISSUE THREAD

**Issue by webaddicto** [angristan/wireguard-install#153]
I have tested the script in a Scaleway VPS and WireGuard was installed correctly (good job!).

Only one issue, in the generated client config file it looks like Endpoint uses local IP:

`Endpoint = 10.64.222.29:51411`

It should use VPS public IP address.

After changing it with the public IP address all worked fine.

**Comment by randomshell** [comment]
The script gets the IP from the default interface and assumes it is a public one. Before actually using it in the configuration, the installer asks you to confirm it is indeed the public IP of the server (you can input a public hostname too, for example myvps.ovh), you must have confirmed it by accident. You can change it inside `/etc/wireguard/params` to be applied for new clients.

**Comment by angristan** [comment]
Yeah, the first question that is asked is:

```
root@server:~# ./wireguard-install.sh
Welcome to the WireGuard installer!
The git repository is available at: https://github.com/angristan/wireguard-install

I need to ask you a few questions before starting the setup.
You can keep the default options and just press enter if you are ok with them.

IPv4 or IPv6 public address: ....
```
