### ISSUE TITLE
Docs for Raspberry Pi

### ISSUE THREAD

**Issue by angristan** [angristan/wireguard-install#17]
Works fine, except you have to use the stock kernel (no raspi-update) + install headers.

- https://www.raspberrypi.org/documentation/linux/kernel/updating.md
- https://www.raspberrypi.org/documentation/linux/kernel/headers.md

**Comment by LiveChief** [comment]
How do u even detect rasberry pi, doesn't it just show up as Debian?

**Comment by angristan** [comment]
Raspbian is indeed not detected atm, it does not even recognise Debian.

**Comment by LiveChief** [comment]
```
elif [ -e /etc/debian_version ]; then
    DISTRO=$( lsb_release -is )
```

use that, it will work to recognize Debian on the latest version of pi desktop, i tested something

**Comment by LiveChief** [comment]
![image](https://user-images.githubusercontent.com/16564273/59133831-336d5f80-8947-11e9-8d31-0a71083ac9df.png)
![image](https://user-images.githubusercontent.com/16564273/59133849-46802f80-8947-11e9-893b-a3e9c88617d4.png)


## Command works on all versions of Debian, even the debian running on chromebook

**Comment by fjleon1980** [comment]
/etc/os-release returns ID=raspbian and the script expects either debian or ubuntu. that file also has ID_LIKE=debian

don't know if that variable exists in debian or ubuntu so the script could be changed to monitor it instead

**Comment by ThePigPeppa** [comment]
@angristan please accept https://github.com/angristan/wireguard-install/pull/37 this issue will be fixed.
