### ISSUE TITLE
add forwarding /etc/sysctl.conf

### ISSUE THREAD

**Issue by ah1102** [angristan/wireguard-install#174]
Please add to the script (uncommit line: _net.ipv4.ip_forward = 1_):

```
# nano /etc/sysctl.conf 
net.ipv4.ip_forward = 1
```

apply new setting:

```
# sysctl -p
net.ipv4.ip_forward = 1
```

To do this, add this command to the script:
 
```
 # Turn on forwarding in sysctl.conf
 sed -i '/net.ipv4.ip_forward=1/s/^#//g' /etc/sysctl.conf
```

![Снимок экрана 2021-01-12 в 20 03 24](https://user-images.githubusercontent.com/58341369/104348047-5643fa80-5512-11eb-994e-44e19a1d0fb3.png)

**Comment by angristan** [comment]
It's already there https://github.com/angristan/wireguard-install/blob/21b5e56eea117ae0c509591a5fa1c9d79b37f383/wireguard-install.sh#L193-L197
