### ISSUE TITLE
New Feature - Problem

### ISSUE THREAD

**Issue by GiannisRallis** [angristan/wireguard-install#177]
Hello i want your help. 

I want to implement a wireguard server with /8 subnet. The script support with /24. How to add clients using the same script if you have changed the subnet mask inside the wireguard configuration file.

Another issue is to save qr code as image. If someone want to create massive qrcodes. Is there a way to edit the line 
`qrencode -t ansiutf8 -l L <"${HOME_DIR}/${SERVER_WG_NIC}-client-${CLIENT_NAME}.conf"` to save conf and imageqrcode

**Comment by angristan** [comment]
The script does not support subnets other than /24 for now.
