### ISSUE TITLE
error

### ISSUE THREAD

**Issue by qszx** [angristan/wireguard-install#179]
![image](https://user-images.githubusercontent.com/19207461/106258889-72a59e00-6259-11eb-8f21-4ad96d2b1617.png)

**Comment by angristan** [comment]
We can see in the background that the installation process didn't went well 
> wg: comment not found

Can you please scroll up and show us what happened at the beginning of the script?

**Comment by qszx** [comment]
┌──(root💀kali)-[/home/m/Downloads]
└─# curl -O https://raw.githubusercontent.com/angristan/wireguard-install/master/wireguard-install.sh
chmod 777 wireguard-install.sh
./wireguard-install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14866  100 14866    0     0   2142      0  0:00:06  0:00:06 --:--:--  3053
Welcome to WireGuard-install!
The git repository is available at: https://github.com/angristan/wireguard-install

It looks like WireGuard is already installed.

What do you want to do?
   1) Add a new user
   2) Revoke existing user
   3) Uninstall WireGuard
   4) Exit
Select an option [1-4]: 1

Tell me a name for the client.
The name must consist of alphanumeric character. It may also include an underscore or a dash and can't exceed 15 chars.
Client name: ppp
Client's WireGuard IPv4: 10.66.66.3
Client's WireGuard IPv6: fd42:42:42::3
./wireguard-install.sh: line 273: wg: command not found
./wireguard-install.sh: line 274: wg: command not found
./wireguard-install.sh: line 275: wg: command not found
Failed to restart wg-quick@wg0.service: Unit wg-quick@wg0.service not found.

Here is your client config file as a QR Code:
./wireguard-install.sh: line 309: qrencode: command not found
It is also available in /root/wg0-client-ppp.conf
                                                                                                        @angristan

**Comment by qszx** [comment]
> 我们可以在后台看到安装过程进行得不好
> 
> > wg：未找到评论
> 
> 您能否向上滚动并向我们展示脚本开头发生了什么？

                                                                                                                              
┌──(root💀kali)-[/home/m/Downloads]
└─# curl -O https://raw.githubusercontent.com/angristan/wireguard-install/master/wireguard-install.sh
chmod 777 wireguard-install.sh
./wireguard-install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14866  100 14866    0     0   2142      0  0:00:06  0:00:06 --:--:--  3053
Welcome to WireGuard-install!
The git repository is available at: https://github.com/angristan/wireguard-install

It looks like WireGuard is already installed.

What do you want to do?
   1) Add a new user
   2) Revoke existing user
   3) Uninstall WireGuard
   4) Exit
Select an option [1-4]: 1

Tell me a name for the client.
The name must consist of alphanumeric character. It may also include an underscore or a dash and can't exceed 15 chars.
Client name: ppp
Client's WireGuard IPv4: 10.66.66.3
Client's WireGuard IPv6: fd42:42:42::3
./wireguard-install.sh: line 273: wg: command not found
./wireguard-install.sh: line 274: wg: command not found
./wireguard-install.sh: line 275: wg: command not found
Failed to restart wg-quick@wg0.service: Unit wg-quick@wg0.service not found.

Here is your client config file as a QR Code:
./wireguard-install.sh: line 309: qrencode: command not found
It is also available in /root/wg0-client-ppp.conf

**Comment by angristan** [comment]
Please run `rm -rf /etc/wireguard` and try again

**Comment by qszx** [comment]
> Please run `rm -rf /etc/wireguard` and try again

No PrivateKey generated

**Comment by angristan** [comment]
Please post the full output.

**Comment by qszx** [comment]
> Please post the full output.

                                                                                                                                                                                                  
┌──(root💀kali)-[/home/m/Downloads]
└─# ./wireguard-install.sh        

Welcome to WireGuard-install!
The git repository is available at: https://github.com/angristan/wireguard-install

It looks like WireGuard is already installed.

What do you want to do?
   1) Add a new user
   2) Revoke existing user
   3) Uninstall WireGuard
   4) Exit
Select an option [1-4]: 
Select an option [1-4]: 1

Tell me a name for the client.
The name must consist of alphanumeric character. It may also include an underscore or a dash and can't exceed 15 chars.
Client name: qq
Client's WireGuard IPv4: 10.66.66.3
Client's WireGuard IPv6: fd42:42:42::3
./wireguard-install.sh: line 273: wg: command not found
./wireguard-install.sh: line 274: wg: command not found
./wireguard-install.sh: line 275: wg: command not found
Failed to restart wg-quick@wg0.service: Unit wg-quick@wg0.service not found.

Here is your client config file as a QR Code:
./wireguard-install.sh: line 309: qrencode: command not found
It is also available in /root/wg0-client-qq.conf
                                                                                                                                                                                                                                            
┌──(root💀kali)-[/home/m/Downloads]
└─# cat /root/wg0-client-qq.conf  
[Interface]
PrivateKey = 
Address = 10.66.66.3/32,fd42:42:42::3/128
DNS = 94.140.14.14,94.140.15.15

[Peer]
PublicKey = 
PresharedKey = 
Endpoint = 192.168.61.128:52525
AllowedIPs = 0.0.0.0/0,::/0

**Comment by angristan** [comment]
Please post the full output of the script **right after** `rm -rf /etc/wireguard`

**Comment by qszx** [comment]
> Please post the full output of the script **right after** `rm -rf /etc/wireguard`

rm -rf /etc/wireguard has been executed

**Comment by angristan** [comment]
Yes, so please run the script and post the output. 

> It looks like WireGuard is already installed.

Means the script finds an existing `/etc/wireguard/params` file.

**Comment by qszx** [comment]
> Yes, so please run the script and post the output.
> 
> > It looks like WireGuard is already installed.
> 
> Means the script finds an existing `/etc/wireguard/params` file.

                                                                                                                                                                                        
┌──(root💀kali)-[/home/m/Downloads]
└─# rm -rf /etc/wireguard                                                                                                                                                                                                               1 ⨯
                                                                                                                                                                                                                                            
┌──(root💀kali)-[/home/m/Downloads]
└─# ./wireguard-install.sh      

Welcome to the WireGuard installer!
The git repository is available at: https://github.com/angristan/wireguard-install

I need to ask you a few questions before starting the setup.
You can leave the default options and just press enter if you are ok with them.

IPv4 or IPv6 public address: 192.168.61.128
Public interface: eth0
WireGuard interface name: wg0
Server's WireGuard IPv4: 10.66.66.1
Server's WireGuard IPv6: fd42:42:42::1
Server's WireGuard port [1-65535]: 54169
First DNS resolver to use for the clients: 94.140.14.14
Second DNS resolver to use for the clients (optional): 94.140.15.15

Okay, that was all I needed. We are ready to setup your WireGuard server now.
You will be able to generate a client at the end of the installation.
Press any key to continue...
./wireguard-install.sh: line 162: wg: command not found
./wireguard-install.sh: line 163: wg: command not found
* Applying /etc/sysctl.d/30-postgresql-shm.conf ...
* Applying /usr/lib/sysctl.d/50-pid-max.conf ...
kernel.pid_max = 4194304
* Applying /etc/sysctl.d/99-sysctl.conf ...
* Applying /usr/lib/sysctl.d/protect-links.conf ...
fs.protected_fifos = 1
fs.protected_hardlinks = 1
fs.protected_regular = 2
fs.protected_symlinks = 1
* Applying /etc/sysctl.d/wg.conf ...
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
* Applying /etc/sysctl.conf ...
Failed to start wg-quick@wg0.service: Unit wg-quick@wg0.service not found.
Failed to enable unit: Unit file wg-quick@wg0.service does not exist.

WARNING: WireGuard does not seem to be running.
You can check if WireGuard is running with: systemctl status wg-quick@wg0
If you get something like "Cannot find device wg0", please reboot!

Tell me a name for the client.
The name must consist of alphanumeric character. It may also include an underscore or a dash and can't exceed 15 chars.
Client name: ss
Client's WireGuard IPv4: 10.66.66.2
Client's WireGuard IPv6: fd42:42:42::2
./wireguard-install.sh: line 273: wg: command not found
./wireguard-install.sh: line 274: wg: command not found
./wireguard-install.sh: line 275: wg: command not found
Failed to restart wg-quick@wg0.service: Unit wg-quick@wg0.service not found.

Here is your client config file as a QR Code:
./wireguard-install.sh: line 309: qrencode: command not found
It is also available in /root/wg0-client-ss.conf
If you want to add more clients, you simply need to run this script another time!
                                                                                                                                                                                                                                            
┌──(root💀kali)-[/home/m/Downloads]
└─# cat /root/wg0-client-ss.conf
[Interface]
PrivateKey = 
Address = 10.66.66.2/32,fd42:42:42::2/128
DNS = 94.140.14.14,94.140.15.15

[Peer]
PublicKey = 
PresharedKey = 
Endpoint = 192.168.61.128:54169
AllowedIPs = 0.0.0.0/0,::/0

**Comment by qszx** [comment]
> Yes, so please run the script and post the output.
> 
> > It looks like WireGuard is already installed.
> 
> Means the script finds an existing `/etc/wireguard/params` file.

                                                                                                                                                                                                              
┌──(root💀kali)-[/home/m/Downloads]
└─# /etc/wireguard/params file                                                                                                                                                                                                          1 ⨯
zsh: permission denied: /etc/wireguard/params

**Comment by angristan** [comment]
Ok, it looks like you're skipping this part:

https://github.com/angristan/wireguard-install/blob/21b5e56eea117ae0c509591a5fa1c9d79b37f383/wireguard-install.sh#L121-L155

I see you are running Kali, maybe the script doesn't work well with it.

In order to be able to debug that, could please once again remove `/etc/wireguard` and run the script again, but like this:

```
bash -x wireguard-install.sh
```

With this we will be able to see your OS details.

Thanks!

**Comment by qszx** [comment]
> Ok, it looks like you're skipping this part:
> 
> https://github.com/angristan/wireguard-install/blob/21b5e56eea117ae0c509591a5fa1c9d79b37f383/wireguard-install.sh#L121-L155
> 
> I see you are running Kali, maybe the script doesn't work well with it.
> 
> In order to be able to debug that, could please once again remove `/etc/wireguard` and run the script again, but like this:
> 
> ```
> bash -x wireguard-install.sh
> ```
> 
> With this we will be able to see your OS details.
> 
> Thanks!

]
└─# cat /root/wg0-client-tt.conf
[Interface]
PrivateKey = AGrvAtX87Oe8QBInPvUNNNqS+Iw6JJ1IHGDYLb7PBHI=
Address = 10.66.66.2/32,fd42:42:42::2/128
DNS = 94.140.14.14,94.140.15.15

[Peer]
PublicKey = uKF7eiODCnPBRx1QzAFPyXUvPgD7tbXWRhRd6ywKjGI=
PresharedKey = 2YvxySVguWrolp5235Sid2TjQUFkRtkUk/i3Q/oDwF8=
Endpoint = 192.168.61.128:63744
AllowedIPs = 0.0.0.0/0,::/0
                 


Thanks
