### ISSUE TITLE
OPENVZ

### ISSUE THREAD

**Issue by Arioshoma** [angristan/wireguard-install#182]
Is this possible to use this script on OpenVZ servers?
Is this possible to change ports?

**Comment by jaminmc** [comment]
If your host has a new enough kernel with Wireguard in it, then yes, with my pull request. https://github.com/angristan/wireguard-install/pull/184

You can test if it works by running `ip link add wg999 type Wireguard`. If it creates the interface, then you are good. 

If not, then you will have to try going with either Wireguard-go, or [BoringTun](https://github.com/cloudflare/boringtun). If I get some spare time in the future, I may try to add BoringTun to this script as a backup option when the Wireguard test fails. As BoringTun seems to preform better than WireGuard-go.

**Comment by alicemq** [comment]
Strangely on Hostinger VPS, OPENVZ is running with 5.4.0 kernel, but this command fails, while ` ip link add dev wg0 type wireguard` works.

**Comment by jaminmc** [comment]
Until they merge my Pull request, it will fail.

Try:
```bash
git clone https://github.com/jaminmc/wireguard-install
./wireguard-install/wireguard-install.sh
```
and it will install it from my fork.
