### ISSUE TITLE
pls add Fail2Ban

### ISSUE THREAD

**Issue by ah1102** [angristan/wireguard-install#183]
Please add to the script the ability to install the Fail2Ban program as well. To protect the server

**Comment by jaminmc** [comment]
WireGuard doesn't need fail2ban. The protocol doesn't even respond to a host if the public key, or ip doesn't match the allowed ip's. So it is virtually impossible for someone to brute force their way into your server.  The script even picks a random port. So it isn't using common ports.  

Now, everyone running a Linux server should harden their ssh. Like doing these: https://linuxhandbook.com/ssh-hardening-tips/

**Comment by angristan** [comment]
Agreed :)
