### ISSUE TITLE
rules aren't flushing in tables if iptables-persistent is installed!

### ISSUE THREAD

**Issue by diyaa59** [angristan/wireguard-install#199]
I don't know if anyone have ever encountered this issue before or if you guys even consider it as an issue!

every time I reboot my system I realize that there are some rules in my chains that aren't in the right order or duplicated which messes up the role of iptables!

I can simply add a script at start up to flush all the rules and add my rules in the desired order and then start wireguard tunnel, so that iptables would function properly!
 
Is this something that you guys are aware of?

**Comment by angristan** [comment]
Only a few rules are set when wireguard starts:

https://github.com/angristan/wireguard-install/blob/bd37d606f1c77a3c74c8fe76d21ac0db1391d64c/wireguard-install.sh#L189-L190

It is your job to manage the other rules on your machine 🙂

**Comment by diyaa59** [comment]
I totally understand that wireguard sets the rules once it starts, but if there is ever a surprising restart and rules have been saved by the iptables-persistent package the rules will be duplicated the next time you bring the interface up on the server!
