### ISSUE TITLE
Enable Debian Testing

### ISSUE THREAD

**Issue by beatquantum** [angristan/wireguard-install#203]
If we stick to Debian Buster, there is the need for all the circus around Buster Backports in apt sources. However, Debian Testing already has wireguard included and it perhaps requires wireguard tools on top. 

I have tried to over-ride the debian buster constraint by modifying the script; but the subsequent problems are around wg-up / wg-down rather than the buster dependency. Just a suggestion.

**Comment by angristan** [comment]
We had issue with testing, so I moved to backports instead: https://github.com/angristan/wireguard-install/commit/6e518633f340b8281f032ed47d07f61b4d91fe59

This is also suggested on https://www.wireguard.com/install/:

> Users with Debian releases older than Bullseye should enable backports.
