### ISSUE TITLE
Issue while adding client IPv4: can't backslash to correct

### ISSUE THREAD

**Issue by ava1973** [angristan/wireguard-install#204]
While creating a user on a server having IP 192.168.40.93. The script proposes as client IP: 192.168.40.92 (ok)
But i want to correct to lets says something like 192.168.40.200.
And here the issue: can backslash one time to remove the last digit '3'? 
But cant do it again to remove two digit '93'.

thanks for this great tools (it works fluently if i use one ip 192.168.40.9x)

Below the execution of wireguard-install.sh
`...
What do you want to do?
   1) Add a new user
   2) Revoke existing user
   3) Uninstall WireGuard
   4) Exit
Select an option [1-4]: 1

Tell me a name for the client.
The name must consist of alphanumeric character. It may also include an underscore or a dash and can't exceed 15 chars.
Client name: xxxxxxxxxx
Client's WireGuard IPv4: 192.168.40.92
`

**Comment by angristan** [comment]
Thanks for the report! Should be fixed.
