### ISSUE TITLE
Support for Alpine Linux

### ISSUE THREAD

**Issue by FireMasterK** [angristan/wireguard-install#205]
Title, it uses `apk` as a package manager, and open-rc for services.

**Comment by angristan** [comment]
I will close this for now:

- Alpine is not available by default on the cloud providers I use (Do, Vultr, Hetzner, Scaleway, etc), so it's difficult for me to implement and maintain
- Alpine not using Systemd will add (a bit) of complexity vs the rest of the supported distributions.

**Comment by romain-neil** [comment]
As what I found, alpine seems to be available on vultr starting few years agao ...
[](https://www.vultr.com/docs/how-to-install-an-alpine-linux-server-at-vultr/)
