### ISSUE TITLE
Accept environment variables as answers.

### ISSUE THREAD

**Issue by Leopere** [angristan/wireguard-install#21]
Would it be unreasonable to imagine a world where your Q&A system could be automated with the addition of bash environment variables?  I think this would be incredibly useful if you already know the answers you want to give.

Otherwise, you could even have an option like $WIREGUARD-INSTALL-RECOMMENDS=True and it would just pick whatever you recommend by default and skip all other questions.

**Comment by angristan** [comment]
Something like https://github.com/angristan/openvpn-install/issues/261

**Comment by liberodark** [comment]
https://github.com/angristan/wireguard-install/pull/46 if you want have possibility to make this but have add a good system -install or -remove next is for add more clients

**Comment by randomshell** [comment]
> Something like [angristan/openvpn-install#261](https://github.com/angristan/openvpn-install/issues/261)

https://github.com/angristan/openvpn-install/pull/592 should be considered too

**Comment by Leopere** [comment]
It really wouldn't be big trouble to add a function for checking the state of a variable, if the variable.

https://www.cyberciti.biz/faq/unix-linux-bash-script-check-if-variable-is-empty/ that can be fairly easily inserted in near the beginning and then the rest of the script can function basically the same.  This way you could use this in headless deployments.

**Comment by randomshell** [comment]
> It really wouldn't be big trouble to add a function for checking the state of a variable, if the variable.

I can't really work on it until my refactoring PRs are reviewed and eventually merged as they conflict with each other and working on master isn't an option. After if you like you can open a PR for this too, the codebase will be similar to the openvpn-install repo.

**Comment by Leopere** [comment]
Hey I’m in zero rush in the meantime I’ll just keep using that
complexorganizations script.

**Comment by AndreiG6** [comment]
This is actually way easier than using if's and should not require any major code changes. **Ignore everything you see in that cyberciti.biz link.** You can simply use bash variable substitution. For example:

```
$ cat things.sh
echo ${lolwat:-things}
$ bash things.sh 
things
$ 
```

vs

```
$ lolwat=omgursh bash things.sh 
omgursh
$ 
```

**Comment by Leopere** [comment]
Makes sense to me but it might be keen to call a check as a function.

**Comment by AndreiG6** [comment]
Why have a function check for a variable and replace the default value vs
just allowing substitution on the default var. Bash variable substitution
is there to avoid extra checks and have a viable default fallback

**Comment by randomshell** [comment]
We aren't going to use functions but variable substitution like it was already done in the openvpn-install repo https://github.com/angristan/openvpn-install/blob/eca5be8aacc54a570bb3c5306d8764e1be3cab79/openvpn-install.sh#L603-L605

**Comment by Leopere** [comment]
Eh that could be fine i do like that solution but just feels brutish like
there’s a lot of potential failure modes where if there’s a good system for
capturing bad inputs in a callable bash function. Just making suggestions
I’m not able to spend time doing it.

If my suggestions get in the way obviously just do it there faster way.
