### ISSUE TITLE
setting key "net.ipv4.conf.all.promote_secondaries": Invalid argument

### ISSUE THREAD

**Issue by Semelovich** [angristan/wireguard-install#219]
When running the install script I get _setting key "net.ipv4.conf.all.promote_secondaries": Invalid argument error_

Here is the install log https://pastebin.com/u5wdQsx4

I checked /usr/lib/sysctl.d/50-default.conf  and here is the relevant lines:

_Promote secondary addresses when the primary address is removed_
net.ipv4.conf.default.promote_secondaries = 1
net.ipv4.conf.*.promote_secondaries = 1
-net.ipv4.conf.all.promote_secondaries

Shouldn't this section look like

_Promote secondary addresses when the primary address is removed_
net.ipv4.conf.default.promote_secondaries = 1
net.ipv4.conf.all.promote_secondaries = 1

Regards

**Comment by angristan** [comment]
That's an issue with your provider, the script does not handle this file:

https://github.com/angristan/wireguard-install/blob/9bce7d6e827ed9fc8c5e02a5e03fcd916f6fd37d/wireguard-install.sh#L190-L194
