### ISSUE TITLE
CentOS Stream installation failure - cannot install the best candidate for the job

### ISSUE THREAD

**Issue by vincejv** [angristan/wireguard-install#231]
Hi,

Seems like I couldn't use this script to install `Wireguard` sucessfully on CentOS Stream 8.

I have encountered this error during execution:
```
Error:
 Problem: cannot install the best candidate for the job
  - nothing provides kernel(__skb_flow_dissect) = 0xd82bed9c needed by kmod-wireguard-3:1.0.20210424
  - nothing provides kernel(flow_keys_basic_dissector) = 0xa7e38f12 needed by kmod-wireguard-3:1.0.2
  - nothing provides kernel(ipv6_stub) = 0xf3965b90 needed by kmod-wireguard-3:1.0.20210424-1.el8_3.
  - nothing provides kernel(totalram_pages) = 0xde9360ba needed by kmod-wireguard-3:1.0.20210424-1.e
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candid
./wireguard-install.sh: line 159: wg: command not found
./wireguard-install.sh: line 160: wg: command not found
910
```

Seems like the script needs to be updated for this error message, also, the script continues to execute even though wireguard was not installed, this should be handled.

**Comment by trettet** [comment]
Was able to follow [this online guide](https://www.cyberciti.biz/faq/centos-8-set-up-wireguard-vpn-server/) instead to install wireguard

use the following command `sudo yum install wireguard-dkms wireguard-tools` instead of `sudo dnf install kmod-wireguard wireguard-tools`,

**Comment by angristan** [comment]
A PR to add support for CentOS Stream would be appreciated :)
