### ISSUE TITLE
Add Support for Openvz 7

### ISSUE THREAD

**Issue by pooryamoh** [angristan/wireguard-install#25]
Openvz 7 can have kernel 4.15 so wireguard should work on that.

**Comment by risturiz** [comment]
I have wireguard-go working on OpenVz 6... Not the best option, but its a nice alternative

**Comment by prajwalkoirala23** [comment]
````
TITLE: compat: support running in OpenVZ environments
COMMIT: https://git.zx2c4.com/WireGuard/commit/?id=08f1bfe29a08d9f10f9fa4c47e07a3501a4a8c8a

+#ifdef CONFIG_VE
+#include <linux/netdev_features.h>
+#ifdef NETIF_F_VIRTUAL
+#undef NETIF_F_LLTX
+#define NETIF_F_LLTX (__NETIF_F(LLTX) | __NETIF_F(VIRTUAL))
+#endif
+#endif
+
```

**Comment by thpryrchn** [comment]
On my fork, I have made it work in Ubuntu containers, and detect if a wireguard kernel module is available. If not, it will install the wireguard-go version. wg-quick does try to load the kernel module before it falls back to the wireguard-go implementation.

My fork also asks how many clients you want to make (Default 3), and has another script to make more clients.

https://github.com/thpryrchn/wireguard-install

**Comment by bmullan** [comment]
@thpryrchn I am a long time LXC and now LXD user and saw in your [wireguard-install.sh](https://github.com/thpryrchn/wireguard-install/blob/master/wireguard-install.sh) that you mention LXC but is that LXD's LXC or the previous LXC (hope you know what I mean here)? 

Thanks..
Brian

**Comment by thpryrchn** [comment]
@bmullan I am running it on my server running LXD 3.18, and a VPS in Germany that is a LXC container, and I have no Idea what it has for its LXC version.

Here is what I have for the configuration on my LXD container...
`architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 18.04 LTS amd64 (release) (20190918)
  image.label: release
  image.os: ubuntu
  image.release: bionic
  image.serial: "20190918"
  image.version: "18.04"
  limits.cpu.allowance: 30%
  limits.memory: 512MB
  linux.kernel_modules: ip_tables,ip6_tables,ip6table_filter,ip6table_nat,ip6t_MASQUERADE,ip6t_REJECT,ip6t_rt,netlink_diag,nf_nat,overlay,br_netfilter,wireguard
  volatile.base_image: 9ff5784302bfd6d556ac4c4c1176a37e86d89ac4d1aced14d9388919fa58bee8
...`

I'm probably passing through too much kmods to it, but it works great!

**Comment by bmullan** [comment]
@thpryrchn - I live in Raleigh .. see you are close.   Could you email me (bmullan.mail@gmail.com)
