### ISSUE TITLE
Subnetmask for client check /24

### ISSUE THREAD

**Issue by dawdad** [angristan/wireguard-install#259]
in line 249 : IPV4_EXISTS=$(grep -c "$CLIENT_WG_IPV4/24" "/etc/wireguard/${SERVER_WG_NIC}.conf")
is it correct that you check for /24 and not for /32, in line 310 you create user entrys for wg0.conf withs static /32.

**Comment by angristan** [comment]
Fixed by https://github.com/angristan/wireguard-install/commit/0a612774ac0fe2af6a6ce2f0ab8c70ec27702ae8
