### ISSUE TITLE
Not working on DietPi - 

### ISSUE THREAD

**Issue by UNlDAN** [angristan/wireguard-install#27]
Here is the error, I already tried sudo apt install linux-headers-$(uname -r)

Error:

Job for wg-quick@wg0.service failed because the control process exited with error code.
See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.

**Comment by angristan** [comment]
Then please post the logs (`ystemctl status wg-quick@wg0.service"`)

**Comment by UNlDAN** [comment]
> Then please post the logs (`systemctl status wg-quick@wg0.service"`)

Here"

>  systemctl status wg-quick@wg0.service
● wg-quick@wg0.service - WireGuard via wg-quick(8) for wg0
   Loaded: loaded (/lib/systemd/system/wg-quick@.service; enabled; vendor preset
: enabled)
   Active: failed (Result: exit-code) since Wed 2019-08-07 13:26:06 B
ST; 1min 8s ago
     Docs: man:wg-quick(8)
           man:wg(8)
           https://www.wireguard.com/
           https://www.wireguard.com/quickstart/
           https://git.zx2c4.com/WireGuard/about/src/tools/man/wg-quick.8
           https://git.zx2c4.com/WireGuard/about/src/tools/man/wg.8
  Process: 631 ExecStart=/usr/bin/wg-quick up wg0 (code=exited, status=1
27)
 Main PID: 631 (code=exited, status=127)

Aug 07 13:26:06 DietPi wg-quick[631]: [#] ip -4 address add 10.66.66.1/24 dev wg
0
Aug 07 13:26:06 DietPi wg-quick[631]: [#] ip -6 address add fd42:42:42::1/64 dev
 wg0
Aug 07 13:26:06 DietPi wg-quick[631]: [#] ip link set mtu 1420 up dev wg0
Aug 07 13:26:06 DietPi wg-quick[631]: [#] iptables -t nat -A POSTROUTING -o eth0
 -j MASQUERADE; ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
Aug 07 13:26:06 DietPi wg-quick[631]: /usr/bin/wg-quick: line 248: iptables: com
mand not found
Aug 07 13:26:06 DietPi wg-quick[631]: [#] ip link delete dev wg0

**Comment by angristan** [comment]
Can you install iptables and try again?

**Comment by UNlDAN** [comment]
Tried and worked! Does this version have a similar system to complexorganization's installer where you can view the QR code?

**Comment by angristan** [comment]
I opened #28 to add iptables as a dependency.

As for the qrcode, no we don't but it's easy:

```
qrencode -t ansiutf8 < wg-client.conf
```

I'll keep that in mind for a future update!
