### ISSUE TITLE
Does not work on Ubuntu 21.10

### ISSUE THREAD

**Issue by joep** [angristan/wireguard-install#295]
Script succeeded on install and I was able to connect the client, but no wider connection (e.g., to the internet) was working. After playing for a bit, I installed 18.04 onto the server instead and everything worked flawlessly.

**Comment by UltimaAtomica** [comment]
Same with Debian 11.
In my case, _resolv.conf_ no longer has nameservers after installing and can't be directly edited :
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "resolvectl status" to see details about the actual nameservers.
```

**Comment by abdollahim** [comment]
I had the same problem 

> Script succeeded on install and I was able to connect the client, but no wider connection (e.g., to the internet) was working. After playing for a bit, I installed 18.04 onto the server instead and everything worked flawlessly.

I had the same problem on Ubuntu 21.04 and 21.10
I have it installed on my old Ubuntu 18.04, but it won't work successfully on new installations.
It seems there are some problems with routing, forwarding, DNS, or something like them!

**Comment by XuHuimiao-63111** [comment]
Me neither,this script seems doesn't work well on Ubuntu 21.10，I can connect to my server using ipv4 broadband with NAT 1,and  can get access to the Internet,but it can't work on 4G LTE and other network with ipv6,I think there is something wrong with DNS or NAT forward. BTW,I tested mannual setup everthing not using the sccript and the wireguard works well

**Comment by XuHuimiao-63111** [comment]
After using this script to setup the wireguard, I checked the /etc/sysctl.conf ,the ipv4/ipv6 forward are all not uncommentted,so I think the problem maybe related to iptables or ipv4 forward

**Comment by ch0wner** [comment]
> After using this script to setup the wireguard, I checked the /etc/sysctl.conf ,the ipv4/ipv6 forward are all not uncommentted,so I think the problem maybe related to iptables or ipv4 forward

That is not a problem, the script creates a file at `/etc/sysctl.d/wg.conf` which gets also gets loaded when the scripts runs: `sysctl --system`.  
you can verify this by running : 
```bash
cat /proc/sys/net/ipv4/ip_forwarded # If turn on will be set to 1
```
