### ISSUE TITLE
Add the possibility to add more clients

### ISSUE THREAD

**Issue by angristan** [angristan/wireguard-install#3]

**Comment by lucawen** [comment]
Want to share the strategy with us? Maybe we can start the logic for you...

**Comment by angristan** [comment]
Yes, I'm not sure how to do it yet 😕

**Comment by lucawen** [comment]
So i think i will help to do  this ... and the remove clients... Bash scripts its not my area, python is.. but will be a new challange 🥇

**Comment by nikke11** [comment]
Thank you so much for your amazing blog and script angristan!
To add/remove users maybe you can get some inspiration from:
[https://github.com/faicker/wg-config](https://github.com/faicker/wg-config)

**Comment by angristan** [comment]
Thanks @nikke11!

**Comment by hybtoy** [comment]
@angristan 
Take a look to this script https://github.com/LiveChief/wireguard-install/blob/master/wireguard-server.sh

**Comment by liberodark** [comment]
Im adding that on new release : https://github.com/angristan/wireguard-install/pull/46

**Comment by angristan** [comment]
See https://github.com/angristan/wireguard-install/pull/58. Feedback is appreciated, otherwise I'll merge this in a few days!
