### ISSUE TITLE
resolvconf make dns gone.

### ISSUE THREAD

**Issue by rickicode** [angristan/wireguard-install#306]
please remove resolvconf, because make nameserver on /etc/resolv.conf gone.

**Comment by ch0wner** [comment]
Quoting https://wiki.debian.org/NetworkConfiguration:

> The resolvconf program is generally only necessary when a system has multiple programs that need to dynamically modify the nameserver information. In a simple system where the nameservers do not change often or are only changed by one program, the resolv.conf configuration file is adequate.

Therefore, you can safely remove the package from your system if not needed. If you wish to keep it though..
See how to configure resolvconf correctly: 
https://unix.stackexchange.com/a/80856/447162

**Comment by angristan** [comment]
Unfortunately, this is needed by `wg-quick` 😕
