### ISSUE TITLE
One Wiergard config for all users

### ISSUE THREAD

**Issue by someoneIG** [angristan/wireguard-install#315]
Is only one person allowed to connect to a Wiergard config or is there no restriction?

**Comment by Sinicyn78** [comment]
For each client, you need to create a new account. Otherwise, it will slow down a lot.

**Comment by someoneIG** [comment]
> For each client, you need to create a new account. Otherwise, it will slow down a lot.

How can I change it? I want to use one config for multiple users

**Comment by someoneIG** [comment]
Can someone help me?

**Comment by Sirherobrine23** [comment]
I know it would be nice to have a configuration for several devices, but that doesn't work, you will have to create a new pair of keys and ips to dedicate to the device. Wireguard cannot create just one key pair for more than one device, and it cannot manage multiple devices in the same key pair as it links its keys and its ip address to only that device.
