### ISSUE TITLE
Consider changing the default port to something else

### ISSUE THREAD

**Issue by abumalick** [angristan/wireguard-install#32]
I had a small issue when installing your script, I had previously setup openvpn with your install script on the same server. In consequence I used the same ports for the two services, it took me some time to realize this.

What do you think about changing the default port for the script ?

**Comment by prajwalkoirala23** [comment]
this is a yes

**Comment by angristan** [comment]
https://github.com/angristan/wireguard-install/commit/3b342e531c06160c54d354a55b8fca39fa6c855c

**Comment by abumalick** [comment]
Thank you very much 👍
