### ISSUE TITLE
not working on Oracle Free Cloud

### ISSUE THREAD

**Issue by masterwishx** [angristan/wireguard-install#321]
installed OK but dont have access to internet from Oracle Free Cloud
in installation steps it detect private adress 10.10.x.x on enp0s3 adapter
instead of public 182.x.x.x and if im insert public then i dont have access to internet

**Comment by Sirherobrine23** [comment]
Hello here had the same problem look at this discussions #241, This solves my problem.

**Comment by masterwishx** [comment]
Thanks .
you mean to add these two lines ?

PostUp = iptables -I FORWARD -i ens3 -o wg0 -j ACCEPT; iptables -I FORWARD -i wg0 -j ACCEPT;** iptables -t nat -A POSTROUTING -o ens3 -j MASQUERADE; ip6tables -A FORWARD -i wg0 -j ACCEPT; ip6tables -t nat -A POSTROUTING -o ens3 -j MASQUERADE; sudo iptables -I INPUT -i ens3 -p udp --dport 60000 -m state --state NEW,ESTABLISHED -j ACCEPT

PostDown = iptables -D FORWARD -i ens3 -o wg0 -j ACCEPT; iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o ens3 -j MASQUERADE; ip6tables -D FORWARD -i wg0 -j ACCEPT; ip6tables -t nat -D POSTROUTING -o ens3 -j MASQUERADE; sudo iptables -D INPUT -i ens3 -p udp --dport 60000 -m state --state NEW,ESTABLISHED -j ACCEPT


Also this script cant find my real ouside ip address , it show my private ip in start of install .
founded  another scrit that find it but didnt tryed it ([road warroir wireguard-install](https://github.com/Nyr/wireguard-install)

Also tryed piVPN but also no lack, i will try it again , after i remade instance of Oracle server.
  Thanks

**Comment by Sirherobrine23** [comment]
Oracle defined some rules to block almost all ports on the vm, and on your virtual network.

**Comment by masterwishx** [comment]
> so, the script already adds this rule in the wireguard configuration

you mean this or https://github.com/Nyr/wireguard-install

**Comment by masterwishx** [comment]
i opened the port in oracle cloud  befor running script

**Comment by Sirherobrine23** [comment]
> > so, the script already adds this rule in the wireguard configuration
> 
> you mean this or https://github.com/Nyr/wireguard-install

The https://github.com/angristan/wireguard-install, I don't know other scripts, just a docker image that I'm developing.

**Comment by Sirherobrine23** [comment]
You could put the iptable rules here (`iptables --list`).

**Comment by Sirherobrine23** [comment]
And vm from oracle is what configuration for me to create one here to help you better.

**Comment by masterwishx** [comment]
OK, Thanks a lot 
for now i made new instance and dont know what script to use now?!? 
1. this one (tryed befor,no success to internet side)
2. https://github.com/Nyr/wireguard-install  (there is video on youtube + fix if no internet)
3. pivpn (tryed befor ,no success to internet side)

**Comment by masterwishx** [comment]
> And vm from oracle is what configuration for me to create one here to help you better.

ubuntu 20.4
VM.Standard.A1.Flex -ocpu x4, mem 24gb 
only added udp port for wireguard

**Comment by Sirherobrine23** [comment]
I'll try here and send you the iptables settings.

**Comment by Sirherobrine23** [comment]
# Setup Commands

```shell
curl -O https://raw.githubusercontent.com/angristan/wireguard-install/master/wireguard-install.sh
chmod +x wireguard-install.sh
# in "IPv4 or IPv6 public address:" add VM public IP here.
# and "Server's WireGuard port [1-65535]:" add port opened in oracle cloud dashboard.
sudo ./wireguard-install.sh
sudo iptables -F
sudo iptables-save | sudo tee /etc/iptables/rules.v4
sudo reboot
```
## setup log, with `angristan/wireguard-install`:

```log
ubuntu@wireguardvm:~$ curl -O https://raw.githubusercontent.com/angristan/wireguard-install/master/wireguard-install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15554  100 15554    0     0   106k      0 --:--:-- --:--:-- --:--:--  106k
ubuntu@wireguardvm:~$ chmod +x wireguard-install.sh
ubuntu@wireguardvm:~$ sudo ./wireguard-install.sh
Welcome to the WireGuard installer!
The git repository is available at: https://github.com/angristan/wireguard-install

I need to ask you a few questions before starting the setup.
You can leave the default options and just press enter if you are ok with them.

IPv4 or IPv6 public address: 144.22.149.61
Public interface: enp0s3
WireGuard interface name: wg0
Server's WireGuard IPv4: 10.66.66.1
Server's WireGuard IPv6: fd42:42:42::1
Server's WireGuard port [1-65535]: 51820
First DNS resolver to use for the clients: 8.8.8.8
Second DNS resolver to use for the clients (optional): 1.1.1.1

Okay, that was all I needed. We are ready to setup your WireGuard server now.
You will be able to generate a client at the end of the installation.
Press any key to continue...
...

Tell me a name for the client.
The name must consist of alphanumeric character. It may also include an underscore or a dash and can't exceed 15 chars.
Client name: phone
Client's WireGuard IPv4: 10.66.66.2
Client's WireGuard IPv6: fd42:42:42::2
```ubuntu@wireguardvm:~$ sudo ./wireguard-install.sh
Welcome to the WireGuard installer!
The git repository is available at: https://github.com/angristan/wireguard-install

I need to ask you a few questions before starting the setup.
You can leave the default options and just press enter if you are ok with them.

IPv4 or IPv6 public address: 144.22.149.61
Public interface: enp0s3
WireGuard interface name: wg0
Server's WireGuard IPv4: 10.66.66.1
Server's WireGuard IPv6: fd42:42:42::1
Server's WireGuard port [1-65535]: 51820
First DNS resolver to use for the clients: 8.8.8.8
Second DNS resolver to use for the clients (optional): 1.1.1.1

Okay, that was all I needed. We are ready to setup your WireGuard server now.
You will be able to generate a client at the end of the installation.
Press any key to continue...
...
Tell me a name for the client.
The name must consist of alphanumeric character. It may also include an underscore or a dash and can't exceed 15 chars.
Client name: phone
Client's WireGuard IPv4: 10.66.66.2
Client's WireGuard IPv6: fd42:42:42::2
...
ubuntu@wireguardvm:~$ sudo iptables -F && sudo iptables-save | sudo tee /etc/iptables/rules.v4 
```

## My phone client:
![Screenshot_20220213-142540_WireGuard](https://user-images.githubusercontent.com/50121801/153766949-2284c365-13e1-46a6-8a14-54096c0244e8.png)

**Comment by masterwishx** [comment]
1.did the script found your external ip?
2.and you have access to inet ?
3. do i need run (iptables -F) its delete iptables ?

Thanks a lot , i will try it.

also have some strange problem when i use "reboot" command in ssh,  then i can access by ssh to server (timeout)
also checked by https://www.infobyip.com/sshservertest.php , server 22 port like unvalible ...
so im restaring by cloud by oracle dashboard ...

**Comment by Sirherobrine23** [comment]
1. I didn't have to put it manually because it doesn't look for the external IP.
2. Yes.
3. Yes, because you will have to eliminate the rules defined by oracle that blocks all requests to the vm.

**Comment by masterwishx** [comment]
ah OK Thanks i will try

**Comment by masterwishx** [comment]
but i cant somehow to enter to server now by ssh !!!! after reboot also rebooted by dashboard after this and still cant access to ssh also https://www.infobyip.com/sshservertest.php cant access to 22 port 
i will try later ,i had this proble yesturday also ,and opened ticked but today it was OK...
anyway thanks a lot for help i will try it when will able to connect 
Thanks

**Comment by Sirherobrine23** [comment]
if you don't have ssh access, connect to the vm through the Dashboard, to solve this problem.
You can also send commands to verify the integrity of the vm through the Dashboard.

**Comment by Sirherobrine23** [comment]
also does not put the IP of the wireguard interface in the same cidr of the network interface that access the internet, because this conflict.

**Comment by masterwishx** [comment]
i added upd port in ingress without statles box checked,
also i found i have mtu 9000 on enp0s3 and mtu 8920 on wg0 may mtu case problem ?

also now i have installed other script (https://github.com/Nyr/wireguard-install ) its very same like this but also can find real outside ip ,willbe cool to add it to this script. also i having wireguard OK but no internet somehow ,also used  
"sudo iptables -F && sudo iptables-save | sudo tee /etc/iptables/rules.v4 " but not help.

tomorrow i will unninstall it and install you script and will follow your guide i hope you will help me out .
Thanks





### If $ip is a private IP address, the server must be behind NAT
	if echo "$ip" | grep -qE '^(10\.|172\.1[6789]\.|172\.2[0-9]\.|172\.3[01]\.|192\.168)'; then
		echo
		echo "This server is behind NAT. What is the public IPv4 address or hostname?"
		# Get public IP and sanitize with grep
		get_public_ip=$(grep -m 1 -oE '^[0-9]{1,3}(\.[0-9]{1,3}){3}$' <<< "$(wget -T 10 -t 1 -4qO- "http://ip1.dynupdate.no-ip.com/" || curl -m 10 -4Ls "http://ip1.dynupdate.no-ip.com/")")
		read -p "Public IPv4 address / hostname [$get_public_ip]: " public_ip
		# If the checkip service is unavailable and user didn't provide input, ask again
		until [[ -n "$get_public_ip" || -n "$public_ip" ]]; do
			echo "Invalid input."
			read -p "Public IPv4 address / hostname: " public_ip
		done
		[[ -z "$public_ip" ]] && public_ip="$get_public_ip"
	fi

**Comment by Sirherobrine23** [comment]
the MTU as I remember it won't be a problem as they are the size of the udp packets.
If you are not able to access the NAT must be the iptables rule, I will be waiting for you to help.

**Comment by rayMomoko** [comment]
Not sure if you are using Oracle Linux instead of Ubuntu.
If that is the case, don't forget to allow traffic using firewall-cmd, otherwise traffic may be blocked by the firewall.
There is a ssh service allowed by default in firewall-cmd, but not the others.
I am allowing the wireguard traffic under services as well.
If you don't have any security concerns, you could completely disable the firewall-ncmd

You may allow traffic that you have configured inside the xml with command like below:
`sudo firewall-cmd --zone=public --permanent --add-service=wireguard`

You should then see your service being added in the services:
```
oracle ~]$ sudo firewall-cmd --list-all --zone=public --permanent
public
  target: default
  icmp-block-inversion: no
  interfaces:
  sources:
  services: ftp iperf3-tcp iperf3-udp ssh wireguard zabbix-tcp zabbix-udp
  ports:
  protocols:
  forward: no
  masquerade: yes
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
```

An example of the xml file and the location:
```
oracle ~]$ sudo ls /etc/firewalld/services/wireguard.xml
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>wireguard</short>
  <description>WireGuard open UDP port 60000 for client connections</description>
  <port protocol="udp" port="60000"/>
</service>
```

It is also a good idea to use tcpdump when troubleshooting, to see if packets arrived to the VM or not.

**Comment by rayMomoko** [comment]
> Hello, he is using Ubuntu to apply wireguard server.
> 

Oh, yes, just saw the environment in previous posts.
Thought all the VM.Standard.A1.Flex shape VMs have to use Oracle Linux, seems they are allowing others as well now.

**Comment by xw-l** [comment]
So, reinstall the system, and everything will work out。(BONUS: It really works!)

**Comment by Sirherobrine23** [comment]
he can do that, and it would be nice, but it depends on him, sometimes he doesn't want to recreate the vm by some service he hosts there.

**Comment by masterwishx** [comment]
I unnistalled the script that has wireguard, and will install yours, then I will post all info of wireguard.
I already made new clean instance. After tryed your script and pivpn script.
Also I made backup of clean boot disk after creation of vm.and I don't installed any services befor wireguard. All that I had befor is gone. 
I wanted to make wireguard to work first... 

I installed wireguard on my Unraid home server without any problem in 5-10 min. 
But vps I'm trying for first time. 
If will be problems again I can restore backup or recreate vm. 
Thanks

**Comment by masterwishx** [comment]
Finally installed you script script and still no internet on my phone.
but somehow after: 

sudo iptables -F && sudo iptables-save | sudo tee /etc/iptables/rules.v4 
reboot

i having next iptables with old script ip in it : 
![wireguard1](https://user-images.githubusercontent.com/28630321/154059321-985e8a8b-a78c-45a1-b7b5-a33112278337.jpg)

![wg2](https://user-images.githubusercontent.com/28630321/154060799-b669a6f8-c49f-4e9e-8626-f7ad3e285883.jpg)


![image](https://user-images.githubusercontent.com/28630321/154060138-9b1df18c-071e-43e6-89e5-d4c585e5e2d8.png)

**Comment by masterwishx** [comment]
![wg3](https://user-images.githubusercontent.com/28630321/154061664-ef981aec-8999-431c-9fc6-82fe53da27c8.jpg)

**Comment by Sirherobrine23** [comment]
I suspect you still don't have internet access, can you test on the computer to see if you still don't have internet too?

**Comment by masterwishx** [comment]
Also i have very strange and slow server in oracle i nedd to wait 30 min on reboot and its slow do installs also...

**Comment by masterwishx** [comment]
is it ok that i have ip forward from old script in iptable?

**Comment by masterwishx** [comment]
Yes on comp also no inet

**Comment by Sirherobrine23** [comment]
It's looking like some iptables rule or on the oracle cloud network.

**Comment by Sirherobrine23** [comment]
try this network rules in oracle dashboard.

ingress:
![Captura de tela de 2022-02-15 10-15-57](https://user-images.githubusercontent.com/50121801/154069593-4cb9a51d-7221-40e0-9fa5-f2a5eb99e714.png)

egress:
![Captura de tela de 2022-02-15 10-16-01](https://user-images.githubusercontent.com/50121801/154069612-bd3aa9ed-fd9c-47f3-9ad3-5b1334233236.png)

**Comment by Sirherobrine23** [comment]
my phone accesses normal internet and local vm hosts.

## My phone client
Nginx page:
![Screenshot_20220215-103629_Chrome](https://user-images.githubusercontent.com/50121801/154073784-e8fe592e-1d33-4d5d-979c-6061c26527e4.png)

wireguard config:
![Screenshot_20220215-103934_WireGuard~2](https://user-images.githubusercontent.com/50121801/154073792-0cff3c03-0cf2-4a54-a830-8cc382dc4e22.png)

## Iptables rules

```
# Generated by iptables-save v1.8.4 on Tue Feb 15 13:48:34 2022
*filter
:INPUT ACCEPT [3188:1408807]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [3245:2175416]
:InstanceServices - [0:0]
-A FORWARD -i enp0s3 -o wg0 -j ACCEPT
-A FORWARD -i wg0 -j ACCEPT
COMMIT
# Completed on Tue Feb 15 13:48:34 2022
# Generated by iptables-save v1.8.4 on Tue Feb 15 13:48:34 2022
*nat
:PREROUTING ACCEPT [244:65907]
:INPUT ACCEPT [17:1472]
:OUTPUT ACCEPT [92:7610]
:POSTROUTING ACCEPT [34:3004]
-A POSTROUTING -o enp0s3 -j MASQUERADE
-A POSTROUTING -o enp0s3 -j MASQUERADE
COMMIT
# Completed on Tue Feb 15 13:48:34 2022
```

## Oracle cloud Egress/Ingress Rules:
![Captura de tela de 2022-02-15 10-45-24](https://user-images.githubusercontent.com/50121801/154074378-8d90f03c-070c-465e-ab1b-d9f86535af97.png)
![Captura de tela de 2022-02-15 10-45-28](https://user-images.githubusercontent.com/50121801/154074384-e71ea4fa-6c33-490f-9ce1-d7481571c1e9.png)

**Comment by Sirherobrine23** [comment]
no need to restart to apply iptables rules, I only restart if I renew all rules and save.

**Comment by Sirherobrine23** [comment]
no need to restart to apply iptables rules, I only restart if I renew all rules and save.

**Comment by masterwishx** [comment]
ok

**Comment by masterwishx** [comment]
Also not working.
So I made new instance with new vcn. 
I will try again on new one.

**Comment by masterwishx** [comment]
i installed on new VM and this VM work perfect and fast , not like befor ..
but still no inet connection :-(

during install: 
![wg install](https://user-images.githubusercontent.com/28630321/155186399-b914fd05-107b-4f7e-80df-47c10a5898f8.jpg)

![image](https://user-images.githubusercontent.com/28630321/155189810-6171c6ea-5369-48ca-931c-8e8f52a3bddb.png)

**Comment by masterwishx** [comment]
added to filter like in your iptable but i mising somehow :

-A FORWARD -i enp0s3 -o wg0 -j ACCEPT
-A FORWARD -i wg0 -j ACCEPT

but its not helped i really dont know what to do ?!?
ps: now my vm working OK in case of speed and restart after some seconds ... not like befor ...
ps: like i said befor, installed wireguard in my home Unraid about some minutes without problem :-(

**Comment by Sirherobrine23** [comment]
you have a very suspicious case about accessing your inet.

**Comment by masterwishx** [comment]
I really don't understand where the problem.
Should thouse missing lines must be in rules.v4?
If I use Ip tables - F...... They gone

**Comment by Sirherobrine23** [comment]
`iptables -f` will remove all rules. and release everything.

**Comment by masterwishx** [comment]
![image](https://user-images.githubusercontent.com/28630321/155214201-517a4af0-665f-406c-ba5c-16cc6c403113.png)

is here all OK?

**Comment by Sirherobrine23** [comment]
It's normal.

**Comment by Sirherobrine23** [comment]
The `inet` would be the oracle cloud network, or it would be a network of a computer on your network.

## if in oracle.

1. The network must be on the same vcn and subnet.
2. VMs can communicate with each other.
3. If the VMs are not communicating, they may be on separate networks.

## A local infrastructure of yours.

1. On your router open the ports.
2. Check communication with wireguard server.

## From oracle cloud to on-premises network

If you are going to access a remote machine through wireguard, you have to redirect the ports to the wireguard interface.

**Comment by masterwishx** [comment]
i can ping wg server 10.66.66.1 from phone

**Comment by masterwishx** [comment]
I have only one VM and VCN and Subnet

**Comment by Sirherobrine23** [comment]
It looks like something is blocking the oracle cloud network then.

A simple map:

Phone (allowed)-> Oracle VM (Blocked)-> Internet.

**Comment by masterwishx** [comment]
but i have only one udp opened port after creation of VM

**Comment by Sirherobrine23** [comment]
The standard oracle cloud network allows accessing anything from inside the vm to the outside, but from outside to inside the vm you have to release the port. How was the wireguard port.

**Comment by masterwishx** [comment]
![image](https://user-images.githubusercontent.com/28630321/155218119-63c9225b-6d0a-482d-9c23-6c497aa8ae45.png)
![image](https://user-images.githubusercontent.com/28630321/155218180-cc7d955e-99af-46a5-8dd9-706e4935d4dd.png)

**Comment by masterwishx** [comment]
![image](https://user-images.githubusercontent.com/28630321/155218433-64f5cb03-360d-49e0-9140-6c3d3623e0cd.png)

**Comment by Sirherobrine23** [comment]
I'm going to make a script to check the settings in the VM.
The problem doesn't seem to be in the oracle cloud network.

**Comment by Sirherobrine23** [comment]
If you connect a client and try to access something it gives you an error.

**Comment by masterwishx** [comment]
i will send a picture..

**Comment by masterwishx** [comment]
also will be cool to have a public ip in script automatic like i posted befor from other script or by netc command : 

curl -s ipinfo.io/ip

**Comment by masterwishx** [comment]
![Screenshot_20220223-000329_LanDroid](https://user-images.githubusercontent.com/28630321/155227739-35852ab3-c802-4acc-bbf6-ab234954457f.jpg)
![Screenshot_20220223-000325_LanDroid](https://user-images.githubusercontent.com/28630321/155227750-3b805a25-2865-4858-b0fd-d7d5e426ba59.jpg)
![Uploading Screenshot_20220223-000243_LanDroid
![Screenshot_20220223-000053_Chrome](https://user-images.githubusercontent.com/28630321/155227973-de4148e2-42f7-4fa7-9ca8-1bc9d2b39348.jpg)

**Comment by Sirherobrine23** [comment]
Your wireguard client is not able to resolve the dns, in the wireguard peer settings add some dns that works in your region.

**Comment by masterwishx** [comment]
Strange but using quad dns - 9.9.9.9, 142.112.112.112 for home adguard server in Unraid, also wireguard for unraid, also for unraid net. Without any problem.
I will try to add another dns.

**Comment by masterwishx** [comment]
Yes, it's working :-)
After changed to 1.1.1.1,8.8.8.8
is this mean the oracle blocking Quad Dns in my region?

**Comment by Sirherobrine23** [comment]
From the looks of it, try to ping these dns servers on the wireguard server.

**Comment by masterwishx** [comment]
OK, Thanks i will...
Now I have  slow speed on phone at home wifi 
5Mbp down, 5Mbps up 
Instead of 50Mbps,10Mbps without
Where to look to fix it?

**Comment by masterwishx** [comment]
Also you have:
-A FORWARD -i enp0s3 -o wg0 -j ACCEPT
-A FORWARD -i wg0 -j ACCEPT

in filters in Ip tables. 
Should I add it also?

**Comment by Sirherobrine23** [comment]
Your speed will drop with distance from the VM and your client, in addition to network latency, this is normal.

If you are not able to access the oracle cloud network then you put these rules.

**Comment by masterwishx** [comment]
> If you are not able to access the oracle cloud network then you put these rules.

Do you mean   10.0.0.1, 10.0.0.119 ?
i can ping them from comp client ,its OK

**Comment by Sirherobrine23** [comment]
> OK, vou verificar o acesso... mas a velocidade do oracle deve ser de 50Mbs para baixo e 50Mbps para cima e minha VM em Israel para que os clientes também..
> 
> Isso está na conexão de cabo doméstico com e sem Wireguard e parece muito lento:
> 
> ![velocidade inet](https://user-images.githubusercontent.com/28630321/155362009-4b94a93e-42aa-4a35-9d0f-be490bfd6045.jpg) ![wg velocidade1](https://user-images.githubusercontent.com/28630321/155362036-ddad5744-b7db-4188-a076-3dc84e511417.jpg)

It is normal to have this loss of speed on the internet, for example:

A VM in `San Jose` at oracle I use wireguard to access it here in `São Paulo`, it will drastically reduce the connection speed, because there are several kilometers of network.

**Comment by Sirherobrine23** [comment]
It's always good to get some VM closer to have the ping reduced and the download and upload speed to be higher.

**Comment by Sirherobrine23** [comment]
> > If you are not able to access the oracle cloud network then you put these rules.
> 
> Do you mean 10.0.0.1, 10.0.0.119 ? i can ping them from comp client ,its OK

If you are able to ping or access, you do not need to add these iptables rules.

> Also you have: -A FORWARD -i enp0s3 -o wg0 -j ACCEPT -A FORWARD -i wg0 -j ACCEPT
> 
> in filters in Ip tables. Should I add it also?

**Comment by masterwishx** [comment]
OK,Thanks a lot for you help 
also tryed to  ping from VM : 

![image](https://user-images.githubusercontent.com/28630321/155384516-2b0cc13b-0dc7-4134-8bef-83367564895b.png)

its very , very strange that Quad dns is not pinging from VM , first time i can see it . thats why i cant beleved when was DNS Probe - this DNS problem .  im using it for all in home , same counrty.
but its look like Cloudflare DNS is very quickly from VM so i i wll use it.

Any way thanks for you helping i will try to find problem of speed ...

**Comment by masterwishx** [comment]
@Sirherobrine23 Hi , not fixed problem for now , will check it later but now i have problem i cant get working of ssh tunneling after installed wireguard , befor it was working whithout problem...
im not really good in iptables , i wll post it here maybe you can find where the problem ..

i need to access to tunnel by 127.0.0.1:3000 from browser
to webtop docker  in proxy net port 3000
![image](https://user-images.githubusercontent.com/28630321/167130335-32e8c963-cf4b-49aa-bc84-7a367d16c6a9.png)

![image](https://user-images.githubusercontent.com/28630321/167130525-78abcd15-01aa-4513-88b5-0979788f6b51.png)

![image](https://user-images.githubusercontent.com/28630321/167131165-630140a8-706d-411e-b338-d3a2c4f3a18a.png)

**Comment by Sirherobrine23** [comment]
test this comment here: https://github.com/angristan/wireguard-install/issues/339#issuecomment-1113990268

**Comment by masterwishx** [comment]
Thanks, i will try ...

**Comment by masterwishx** [comment]
Sorry  i wrote not fixed problem i meaned of slow speed, but wireguard is working ....
i have problem of tunneling for now

**Comment by Sirherobrine23** [comment]
how, I understood something wrong, if you're using the server through wireguard, I've noticed that some applications couldn't create the tunnel as ssh, but I don't think it's a problem with wireguard, but I don't think so, sometimes it may be that docker doesn't expose these ports, I've seen it happen.

**Comment by masterwishx** [comment]
Thanks i will check it

**Comment by V-ctor** [comment]
Hi there.
I confirm that issue still exists. But [fix](https://github.com/angristan/wireguard-install/pull/334) from @turbozapekanka solves it.

**Comment by Sirherobrine23** [comment]
It solves yes, Oracle VMs have several rules that block everything, here I just removed these rules and saved, but there is a rule that he added in the pull already serves to solve this case.
