### ISSUE TITLE
revoke doesn't remove generated client file

### ISSUE THREAD

**Issue by tokon2000** [angristan/wireguard-install#322]
If it is installed at /home/user/... the revoke function doesn't remove the generated client file.
${HOME} refers to /root/...

https://github.com/angristan/wireguard-install/blob/4dfbc55cd91861c357c5ff07146c8639fcb89c61/wireguard-install.sh#L357

**Comment by angristan** [comment]
Fixed with https://github.com/angristan/wireguard-install/commit/7565f26b5d2e4542f777001859970378704ce288
