### ISSUE TITLE
Can this support LXD containers across multiple servers/clouds?

### ISSUE THREAD

**Issue by bmullan** [angristan/wireguard-install#35]
Stanislas

I am part of a team project where we use LXD Ubuntu 18.04 containers with Ubuntu 18.04 Host/Servers and recently started looking for a Mesh VPN solution to interconnect servers Hosting LXD containers on multiple Clouds.

Normally LXD on a Host uses dnsmasq and provdes all created containers on that Host with a private 10.x.x.x IP address.

I'd like to be able to interconnect  multiple  Host LXD containers (multiple clouds) to the same L2 or L3 network so they can inter-communicate.

Could you script do this somehow for LXD containers.   I see in your install..sh file mention of LXC and I am assuming for LXD you would be referring to creating the LXD container with:

 
> **$ lxc launch ubuntu:18.04 cn_name -c linux.kernel_modules=wireguard**  
then   

> **$ lxc exec cn_name bash**  
then  

> **\# apt install --no-install-recommends wireguard-tools** 

Thanks for any information or advice.  
Brian

**Comment by angristan** [comment]
Hello,

Wireguard can surely do that, but the goal of the script is not to interconnect servers to each other but to provide a VPN as an alternative to commercial solutions for the general public. I actually use WireGuard on my servers but I manage them with ansible: https://github.com/angristan/ansible-wireguard
