### ISSUE TITLE
Add Oracle Cloud to recommended cloud providers

### ISSUE THREAD

**Issue by matteoturini** [angristan/wireguard-install#350]
Their free tier is the best with multiple more than capable machines free forever, in the user's country.

**Comment by kloklojul** [comment]
i couldnt get it to work in oracle. i setup the ingress and used the script to setup wireguard and i do can connect to the server but i don't have internet access

**Comment by matteoturini** [comment]
It works for me, did you use the Ubuntu image?

Weird thing that fixed it for me was installing `firewalld` and then opening the ports on `firewalld`.

**Comment by kloklojul** [comment]
yea i used the ubuntu image. even with the firewall fully disabled it doesnt work for me. Ofc i can give it a try enabling firewalld and opening the ports their but if i remember correctly i already tried this.

**Comment by matteoturini** [comment]
Firewall disabled _also_ doesn't work for me. You need to install `firewalld` specifically, enable it, and open the ports with `firewall-cmd`. I have no idea why, but it is what it is.

**Comment by kloklojul** [comment]
turns out docker was messing with the interfaces. after a clean install it worked
