### ISSUE TITLE
WireGuard Android app cannot parse generated IPv6 Endpoint address

### ISSUE THREAD

**Issue by jrstrunk** [angristan/wireguard-install#352]
After running the install script (wonderful script by the way), it generated the IPv6 peer as (with different actual values of course):
```bash
[Peer]
PublicKey = CVcJFPr5FPUhQQb1j8H2k0Abg4lDw+dGJVzPPFzJ4js=
PresharedKey = pqO1poiAJStI8nCZcjsI9aD+xXi9zXJKV3wH+VNBG1Y=
Endpoint = 2603:a870:810:10::a0f:6001:56935
AllowedIPs = 0.0.0.0/0,::/0
```

When I tried to import this into the Android WireGuard (v 1.0.20220516 (492)) app, it gave me an unable to import error saying that the Endpoint was unparsable. I edited the config file to instead be `Endpoint = [2603:a870:810:10::a0f:6001]:56935` as I have seen using brackets with IPv6 to distinguish it from the port number before. When I imported this to the app it did not complain at all and I was able to make a connection to the server. I am not experienced enough yet to tell if this fixed the issue for IPv6 or simply hid the issue, as I do not have an IPv6 IP address when connected.

Although I cannot be confident enough in my solution to contribute it to the codebase, I thought I would post this here to let the maintainers know the issue I had and the workaround I made for.

**Comment by angristan** [comment]
Thanks 👍

**Comment by emersonsc** [comment]
problem is back with Android app version v1.0.20230707. Unable to parse when an ipv6 address is given for endpoint
