### ISSUE TITLE
Proposal for small improvement

### ISSUE THREAD

**Issue by francoisPE** [angristan/wireguard-install#361]
Hello,
Thanks a lot for that VERY nice script.
I would propose to add in uninstall function:

ip link delete dev ${SERVER_WG_NIC}

**Comment by angristan** [comment]
The interface should already be automatically removed. What OS did you have this issue on?

**Comment by francoisPE** [comment]
That's true. Interface is automatically removed.
I had that issue when wg exited on bug
I forgot I opened this issue on github !
