### ISSUE TITLE
Error Parsing IP

### ISSUE THREAD

**Issue by QuaverSager** [angristan/wireguard-install#373]
I'm having an issue where every profile I'm making is getting this IP parse issue, and it's affecting our users from being able to use the VPN. 
For example I tried to create a new profile: 

_Client's WireGuard IPv4: 10.69.69.176
Client's WireGuard IPv6: fd42:42:42::176
Unable to parse IP address: `fd42:42:42::130='
Configuration parsing error_

![image](https://user-images.githubusercontent.com/73672342/200689830-2520bf97-07d7-4995-a3c5-f16992ebad0b.png)

Does anyone have some insight or suggestions that may help me resolve this issue?

**Comment by alekskomp** [comment]
Check client with "fd42:42:42::130=" in /etc/wireguard/wg0.conf
And remove "=" symbol
