### ISSUE TITLE
Connected to Wireguard but no internet

### ISSUE THREAD

**Issue by aleminkirali** [angristan/wireguard-install#377]
There seems to be an issue going on at this moment on all the different VPN servers that I am running. All of them are connected but there seems to be no connection to internet. I never looked at what DNS server was used before but it seems to be Adguard(94.140.14.14, 94.140.15.15). When I change the configuration file to use Google DNS everything seems to be fine.
It's impossible for me to ask different users and friends to change all their DNS manually. I also don't see any DNS issue ongoing at Adguard at this moment. What can I do from the server side to fix this issue? I have limited knowledge and sorry for bothering.

**Comment by Proficus** [comment]
I have same problem

**Comment by habnai** [comment]
I have same problem

**Comment by berinaniesh** [comment]
I can confirm, changing the dns to 1.1.1.1 in the conf file fixes the issue

**Comment by aleminkirali** [comment]
The issue is that the Adguard DNS has rate limit on free package that Angristan Wireguard uses. I could not ask all my users to change their config manually. Found someone that did it on the server level to a different DNS. This fixed the issue for me.

**Comment by berinaniesh** [comment]
I just uninstalled wireguard server (using the script) and reinstalled with 1.1.1.1 and 8.8.8.8 as dns servers, but i still have some issue, I have no internet. Not sure what the problem is.

**Comment by cloudslsw** [comment]
i got same issue, change DNS didn't working for me

**Comment by ripkos** [comment]
Had same issue, try following to fix it:
Write your correct **public** IP address when scrip asks it (in my case by default it was private IP).
Open your port that wireguard is listening on (in my case I am hosting on Azure, and by default have all ports closed, therefore had to open it by myself).
Disable firewall to see if it makes any difference. In my case it was `ufw disable` command, after which everything started to work.
