### ISSUE TITLE
Can't install on FreePBX

### ISSUE THREAD

**Issue by 1nn7erplay** [angristan/wireguard-install#386]
[root@freepbx ~]# curl -O https://raw.githubusercontent.com/angristan/wireguard-install/master/wireguard-install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16055  100 16055    0     0  46156      0 --:--:-- --:--:-- --:--:-- 46135
[root@freepbx ~]# chmod +x wireguard-install.sh
[root@freepbx ~]# ./wireguard-install.sh
Looks like you aren't running this installer on a Debian, Ubuntu, Fedora, CentOS, AlmaLinux, Oracle or Arch Linux system
[root@freepbx ~]#

**Comment by angristan** [comment]
This is pretty self explanatory :)
