### ISSUE TITLE
resolvconf screws up raspberry pi

### ISSUE THREAD

**Issue by fjleon1980** [angristan/wireguard-install#43]
i had downloaded a previous version of this script, but the latest one installs resolvconf which breaks DNS on raspbian. You will need to edit /etc/network/interfaces manually and put the dns nameservers manually or you won't be able to resolve hostnames.

IMO script needs to detect raspbian away from debian/ubuntu, even if it means repeating some code. right now it doesn't work anyway unless you manually force OS=debian

**Comment by liberodark** [comment]
Fixed on https://github.com/angristan/wireguard-install/pull/46
