### ISSUE TITLE
Multiple clients on the same machine

### ISSUE THREAD

**Issue by GarfieldsPipe** [angristan/wireguard-install#444]
How do I set it up so that multiple clients (multiple devices) can use the same machine as VPN?
When I simply run the script and load the generated config file onto a second device the connection gets extremely slow and unusable because it's already in use on another device.

**Comment by marhu98** [comment]
Are you using the same keys (i.e the same qr code) on both devices? It works fine for me with three clients with different keys. (To do this, run the wizard again).
