### ISSUE TITLE
Suggestion: generate clients

### ISSUE THREAD

**Issue by realcarbonneau** [angristan/wireguard-install#47]
I made this script to generate a bunch of clients and scripts to configure these clients.  It was inspired by your install script, so feel free to use whatever might be useful for you in these scripts.

https://github.com/realcarbonneau/easy-wireguard

**Comment by liberodark** [comment]
Have work on similar script : https://github.com/angristan/wireguard-install/pull/46

**Comment by angristan** [comment]
https://github.com/angristan/wireguard-install/commit/f0891e7235afca3895ca99d13b8eebad3989e9a0
