### ISSUE TITLE
I can not connect to internet 

### ISSUE THREAD

**Issue by MohMehrnia** [angristan/wireguard-install#472]
I install wire guard successful buy client after connect can not use internet!?!

**Comment by JamesKpP** [comment]
I am having the same problem.

**Comment by ysomad** [comment]
same problem

**Comment by Sirherobrine23** [comment]
what is the system/dist, and where is it hosted?

**Comment by MohMehrnia** [comment]
Ubuntu 22.04, German Hetzner

**Comment by Sirherobrine23** [comment]
I've never used German Hetzner, but does it have a non-system firewall in which it blocks remote access ports?

**Comment by MohMehrnia** [comment]
I can not handshate, is mtu must be special number?

**Comment by Sirherobrine23** [comment]
My power can be any value, but is there a firewall that is managed via the web by your provider?

In Oracle Cloud I need to release the virtual interface ports to be able to use any server, Take a look at this issue:  https://github.com/angristan/wireguard-install/issues/321#issuecomment-1038285584

**Comment by Ppang0405** [comment]
I got same issue in both Vultr and HostHatch providers, I did try Ubuntu 20 and Debian 10, 11, 12. all of theses options have no internet issues.
