### ISSUE TITLE
Ubuntu 18.04 requires PPA

### ISSUE THREAD

**Issue by TheNomad11** [angristan/wireguard-install#48]
Using your script on my Ubuntu 18.04 VPS, the package Wireguard is not found. It needs to be installed first by a PPA as described here https://www.wireguard.com/install/ then it works (I had to install apt-get install software-properties-common as well also

**Comment by angristan** [comment]
The PPA should be added:

https://github.com/angristan/wireguard-install/blob/master/wireguard-install.sh#L85

**Comment by TheNomad11** [comment]
aha I see. so in my case it did not work as software-properties-common was not installed before running your script?
