### ISSUE TITLE
Include QR code generation after successful setup

### ISSUE THREAD

**Issue by patrickmau** [angristan/wireguard-install#49]
Taking inspiration from [here](https://github.com/l-n-s/wireguard-install), it would be much more user-friendly to have a QR code popup at the end of the setup process, allowing mobile users to simply scan the code and have the mobile setup done instantly.

More and more mobile users are interested in WG, this would really help.

Thanks

**Comment by Prajwal-Koirala** [comment]
@patrickmau 

Try this script.
https://github.com/complexorganizations/wireguard-install

**Comment by angristan** [comment]
Indeed!
