### ISSUE TITLE
Netflix Support

### ISSUE THREAD

**Issue by liberodark** [angristan/wireguard-install#50]
Hi,

Would be great to add netflix support in installer.
Im not sure how to make that.
If you have idea can add this on my PR.

Best Regards

**Comment by liberodark** [comment]
For me have fixed that in france with exclude : 52.48.35.66
If you have other ip would be good to send me for make a list.

Best Regards

**Comment by AndreiG6** [comment]
What was the hostname for 52.48.35.66? I'm wondering if we can DNS filter
by host?

**Comment by angristan** [comment]
What do you mean by Netflix support?

**Comment by liberodark** [comment]
Netflix reject VPN.

That is proable range of Netflix.

`108.175.32.0/20,108.175.33.0/24,185.2.220.0/22,185.9.188.0/22,192.173.127.0/24,192.173.64.0/18,192.173.68.0/24,192.173.70.0/24,192.173.72.0/24,192.173.73.0/24,192.173.74.0/24,192.173.75.0/24,192.173.76.0/24,192.173.78.0/24,192.173.79.0/24,198.38.100.0/24,198.38.108.0/24,198.38.109.0/24,198.38.110.0/24,198.38.111.0/24,198.38.112.0/24,198.38.113.0/24,198.38.114.0/24,198.38.115.0/24,198.38.120.0/24,198.38.121.0/24,198.38.122.0/24,198.38.96.0/19,198.38.98.0/24,198.38.99.0/24,198.45.48.0/20,198.45.48.0/24,198.45.49.0/24,198.45.50.0/24,198.45.56.0/24,208.75.76.0/22,23.246.0.0/18,23.246.10.0/24,23.246.11.0/24,23.246.14.0/24,23.246.15.0/24,23.246.16.0/24,23.246.17.0/24,23.246.20.0/24,23.246.2.0/24,23.246.21.0/24,23.246.26.0/24,23.246.27.0/24,23.246.30.0/24,23.246.3.0/24,23.246.31.0/24,23.246.36.0/24,23.246.41.0/24,23.246.44.0/24,23.246.45.0/24,23.246.46.0/24,23.246.47.0/24,23.246.48.0/24,23.246.49.0/24,23.246.50.0/24,23.246.51.0/24,23.246.52.0/24,23.246.54.0/24,23.246.55.0/24,23.246.56.0/24,23.246.57.0/24,23.246.58.0/24,23.246.59.0/24,23.246.6.0/24,23.246.7.0/24,37.77.184.0/21,37.77.186.0/24,37.77.187.0/24,37.77.188.0/24,37.77.189.0/24,45.57.0.0/17,45.57.0.0/24,45.57.100.0/24,45.57.10.0/24,45.57.101.0/24,45.57.102.0/24,45.57.1.0/24,45.57.103.0/24,45.57.11.0/24,45.57.12.0/24,45.57.13.0/24,45.57.14.0/24,45.57.15.0/24,45.57.16.0/24,45.57.17.0/24,45.57.18.0/24,45.57.19.0/24,45.57.20.0/24,45.57.21.0/24,45.57.22.0/24,45.57.23.0/24,45.57.28.0/24,45.57.29.0/24,45.57.36.0/24,45.57.37.0/24,45.57.4.0/24,45.57.44.0/24,45.57.45.0/24,45.57.48.0/24,45.57.49.0/24,45.57.5.0/24,45.57.56.0/24,45.57.58.0/24,45.57.59.0/24,45.57.60.0/24,45.57.6.0/24,45.57.62.0/24,45.57.63.0/24,45.57.64.0/24,45.57.65.0/24,45.57.68.0/24,45.57.69.0/24,45.57.70.0/24,45.57.7.0/24,45.57.71.0/24,45.57.72.0/24,45.57.73.0/24,45.57.74.0/24,45.57.75.0/24,45.57.78.0/24,45.57.79.0/24,45.57.80.0/24,45.57.81.0/24,45.57.82.0/24,45.57.83.0/24,45.57.88.0/24,45.57.89.0/24,45.57.95.0/24,45.57.98.0/24,45.57.99.0/24,64.120.128.0/17,66.197.128.0/17,69.53.224.0/19,69.53.225.0/24,69.53.226.0/24,69.53.228.0/24`

Other rules : 

`AllowedIPs = 34.237.9.27,34.246.46.249,34.250.61.125,34.250.3.119,52.16.8.45,52.22.163.117,52.45.237.93,52.48.35.66,52.70.105.22,54.154.83.0,54.194.155.146,54.86.118.241,54.165.246.104,54.165.246.104,54.154.83.0,34.241.244.104,52.48.35.66,52.214.178.75,54.77.143.196,52.51.252.111,52.18.96.227,34.253.1.11`

**Comment by liberodark** [comment]
Need ip range of netflix for add exception : https://gist.github.com/frk1/8fb578b36bd9a36a48109f412c844a1f

**Comment by Prajwal-Koirala** [comment]
You need a VPS provider that supports Netflix or has an IP that supports IP range Netflix doesn't block.

**Comment by Prajwal-Koirala** [comment]
Please close.

**Comment by AndreiG6** [comment]
Since we're on the topic... are there blocklists available to avoid netflix
detecting it as a vpn? or does it just go by an ip database and figure out
you're using a datacenter ip?

**Comment by angristan** [comment]
> or does it just go by an ip database and figure out you're using a datacenter ip?

yes. There is no blocklist. Bypassing the VPN for Netflix is not a solution, since Netflix uses AWS.
