### ISSUE TITLE
debian 10...wireguard: module verification failed: signature and/or required key missing - tainting kernel

### ISSUE THREAD

**Issue by 33thirtythree** [angristan/wireguard-install#57]
Mar 13 15:13:52 crush kernel: [   16.260799] wireguard: loading out-of-tree module taints kernel.
Mar 13 15:13:52 crush kernel: [   16.260950] wireguard: module verification failed: signature and/or required key missing - tainting kernel
Mar 13 15:13:52 crush kernel: [   16.264175] wireguard: WireGuard 0.0.20200215 loaded. See www.wireguard.com for information.
Mar 13 15:13:52 crush kernel: [   16.264180] wireguard: Copyright (C) 2015-2019 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
root@crush /var/log # uname -a
Linux crush 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

**Comment by angristan** [comment]
https://bugs.launchpad.net/ubuntu/+source/wireguard/+bug/1860206

**Comment by angristan** [comment]
https://lists.zx2c4.com/pipermail/wireguard/2017-September/001684.html

**Comment by angristan** [comment]
is your machine using EFI?

**Comment by 33thirtythree** [comment]
Using bios...   do you know a workaround to get it functional again? btw - thanks for the quick response and the script.

**Comment by angristan** [comment]
Works for me:

```
root@wg:~# dmesg -T | tail -5
[Fri Mar  6 23:21:21 2020] wireguard: loading out-of-tree module taints kernel.
[Fri Mar  6 23:21:21 2020] wireguard: module verification failed: signature and/or required key missing - tainting kernel
[Fri Mar  6 23:21:21 2020] wireguard: WireGuard 0.0.20200215 loaded. See www.wireguard.com for information.
[Fri Mar  6 23:21:21 2020] wireguard: Copyright (C) 2015-2019 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
[Sun Mar  8 11:30:02 2020] conntrack: generic helper won't handle protocol 47. Please consider loading the specific helper module.
root@wg:~# lsmod | grep wireguard
wireguard             229376  0
ip6_udp_tunnel         16384  1 wireguard
udp_tunnel             16384  1 wireguard
```
