### ISSUE TITLE
Getting error after inserting client name

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [angristan/wireguard-install#62]
After entering a name, I'm getting this error with no further output nor file generated 

```
Client name: karl
./wireguard-install.sh: line 183: -4: substring expression < 0
```

**Comment by angristan** [comment]
Are you using the latest version of the script? There is nothing line 183

**Comment by Karlheinzniebuhr** [comment]
Yes, I did
curl -O https://raw.githubusercontent.com/angristan/wireguard-install/master/wireguard-install.sh

**Comment by Karlheinzniebuhr** [comment]
But I found out that the problem the missing linux kernel headers. It seems the error message is just not thrown correctly in the script

**Comment by angristan** [comment]
Mmh that's weird, we should try to find exactly what's going on here. Can I reproduce this? What OS are you using?

**Comment by Karlheinzniebuhr** [comment]
I'm using Proxmox (debian based). You should be able to reproduce it

**Comment by angristan** [comment]
You ran this on the Proxmox hypervisor itself?

**Comment by Karlheinzniebuhr** [comment]
Correct, following the instructions in a troubleshooting guide which said that in order for it to work on containers, it first has to be installed on the hypervisor.

**Comment by angristan** [comment]
OK. Well I'd need you to run the script with `bash -x` otherwise we can't really debug this 🙂

**Comment by randomshell** [comment]
@angristan why I can't find `Client name` prompt in wireguard-install.sh?

**Comment by angristan** [comment]
Indeed.... @Karlheinzniebuhr ?

**Comment by Karlheinzniebuhr** [comment]
Just came back here, I somehow made it work a few days ago. Closing this.
