### ISSUE TITLE
Not working on aws ec2 instance

### ISSUE THREAD

**Issue by boddumanohar** [angristan/wireguard-install#66]
I tried the same example on an AWS EC2 ubuntu instance. I am to connect to VPN but after connecting to internet, I am not able to access internet.

**Comment by boddumanohar** [comment]
Happens even if I open all tcp traffic from anywhere in security groups

**Comment by randomshell** [comment]
Try the comments from #409 until one works.

**Comment by boddumanohar** [comment]
```
echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
iptables -I FORWARD 1 -i ens5 -o wg0 -j ACCEPT
iptables -I FORWARD 1 -i wg0 -o ens5 -j ACCEPT
```
No luck

**Comment by randomshell** [comment]
I'm sorry, I thought I was on the openvpn-install repo when I wrote this answer. I don't know how to help for wireguard.

**Comment by angristan** [comment]
@boddumanohar WireGuard uses UDP, can you verify your security groups again?

**Comment by boddumanohar** [comment]
I opened up all traffic on all protocols, ran: I still not able to connect.

**Comment by boddumanohar** [comment]
I tried this on a t3.nano in us-east-1 region on Ubuntu 18.01 instance on a public subnet.

**Comment by angristan** [comment]
Works for me on EC2. Make sure you typed the public IP of the EC2 when asked. Since the EC2 is behind NAT, the script will prompt for the interface's private IP by default. You can fix that afterwards by updating the endpoint in your config file to the EC2's pub IP

**Comment by abumalick** [comment]
for me it worked only after rebooting the server

**Comment by angristan** [comment]
Probably an issue in loading the kernel module.
