### ISSUE TITLE
wg-quick: `wg0-client-qjL8odh7' does not exist

### ISSUE THREAD

**Issue by chemicalsoup** [angristan/wireguard-install#67]
Server on AWS EC2
(security group for ssh + all tcp and all udp ports listening for my public IP) when script asked I put IPv4 public IP that amazon gave me rest all default.
I am using Arch linux to connect to server. wireguard-tools installed.
wg0-client-qj...conf  copied to /etc/wireguard.
I had openvpn and networkmanager-openvpn installed which i removed after installing wireguard.
following config files did not help either
/etc/NetworkManager/conf.d/unmanaged.conf
[keyfile]
unmanaged-devices=interface-name:wg*

sudo wg-quick up produces the above result

**Comment by chemicalsoup** [comment]
ok I changed the conf file name to wg0.conf
then
`sudo wg showconf wg0 > /etc/wireguard/wg0.conf
sudo wg setconf wg0 /etc/wireguard/wg0.conf
wg-quick up wg0-client

[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip link set mtu 1420 up dev wg0`

**Comment by chemicalsoup** [comment]
I think next step should be routing all my traffic through wg0 interface/tunner/dev.

**Comment by angristan** [comment]
Yes that's what the `AllowedIPs` line does: 

https://github.com/angristan/wireguard-install/blob/6e60d59ee447021afdd9e16c83be933625836125/wireguard-install.sh#L45
