### ISSUE TITLE
Debian 10 x64: Errors when installing | KVM VPS and baremetal

### ISSUE THREAD

**Issue by Archerious** [angristan/wireguard-install#70]
```
./wireguard-install.sh
IPv4 or IPv6 public address: CENSORED
Public interface: ens3
WireGuard interface name: wg0
Server's WireGuard IPv4: 10.66.66.1
Server's WireGuard IPv6: fd42:42:42::1
Server's WireGuard port: 63584
Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://deb.debian.org/debian buster-updates InRelease
Hit:3 http://security.debian.org/debian-security buster/updates InRelease
Hit:4 http://deb.debian.org/debian unstable InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
4 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
linux-headers-4.19.0-8-amd64 is already the newest version (4.19.98-1).
The following packages were automatically installed and are no longer required:
  dkms linux-headers-amd64 wireguard-tools
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
iptables is already the newest version (1.8.2-4).
qrencode is already the newest version (4.0.2-1).
resolvconf is already the newest version (1.79).
The following additional packages will be installed:
  wireguard-dkms
The following NEW packages will be installed:
  wireguard wireguard-dkms
0 upgraded, 2 newly installed, 0 to remove and 4 not upgraded.
Need to get 0 B/259 kB of archives.
After this operation, 1776 kB of additional disk space will be used.
Selecting previously unselected package wireguard-dkms.
(Reading database ... 55611 files and directories currently installed.)
Preparing to unpack .../wireguard-dkms_1.0.20200413-2_all.deb ...
Unpacking wireguard-dkms (1.0.20200413-2) ...
Selecting previously unselected package wireguard.
Preparing to unpack .../wireguard_1.0.20200319-1_all.deb ...
Unpacking wireguard (1.0.20200319-1) ...
Setting up wireguard-dkms (1.0.20200413-2) ...
Loading new wireguard-1.0.20200413 DKMS files...
Building for 4.19.0-8-amd64
Building initial module for 4.19.0-8-amd64
! Bad return status for module build on kernel: 4.19.0-8-amd64 (x86_64)
Consult /var/lib/dkms/wireguard/1.0.20200413/build/make.log for more information.
dpkg: error processing package wireguard-dkms (--configure):
 installed wireguard-dkms package post-installation script subprocess returned error exit status 10
dpkg: dependency problems prevent configuration of wireguard:
 wireguard depends on wireguard-dkms (>= 0.0.20200121-2) | wireguard-modules (>= 0.0.20191219); however:
  Package wireguard-dkms is not configured yet.
  Package wireguard-modules is not installed.

dpkg: error processing package wireguard (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 wireguard-dkms
 wireguard
E: Sub-process /usr/bin/dpkg returned an error code (1)
* Applying /etc/sysctl.d/99-sysctl.conf ...
* Applying /etc/sysctl.d/protect-links.conf ...
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
* Applying /etc/sysctl.d/wg.conf ...
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
* Applying /etc/sysctl.conf ...
Job for wg-quick@wg0.service failed because the control process exited with error code.
See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.
IPv4 Detected
Client's WireGuard IPv4 10.66.66.2
Client's WireGuard IPv6 fd42:42:42::2
First DNS resolver to use for the client: 176.103.130.130
Second DNS resolver to use for the client: 176.103.130.131
Job for wg-quick@wg0.service failed because the control process exited with error code.
See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.

```

```
# journalctl -xe
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit wg-quick@wg0.service has finished with a failure.
--
-- The job identifier is 321 and the job result is failed.
Apr 21 23:27:10 host systemd[1]: Reloading.
Apr 21 23:27:10 host systemd[1]: getty@tty1.service: Current command vanished from the unit file
Apr 21 23:27:32 host systemd[1]: Starting WireGuard via wg-quick(8) for wg0...
-- Subject: A start job for unit wg-quick@wg0.service has begun execution
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit wg-quick@wg0.service has begun execution.
--
-- The job identifier is 409.
Apr 21 23:27:32 host wg-quick[2155]: [#] ip link add wg0 type wireguard
Apr 21 23:27:32 host wg-quick[2155]: RTNETLINK answers: Operation not supported
Apr 21 23:27:32 host wg-quick[2155]: Unable to access interface: Protocol not supported
Apr 21 23:27:32 host wg-quick[2155]: [#] ip link delete dev wg0
Apr 21 23:27:32 host wg-quick[2155]: Cannot find device "wg0"
Apr 21 23:27:32 host systemd[1]: wg-quick@wg0.service: Main process exited, code=exited, status=
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit wg-quick@wg0.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Apr 21 23:27:32 host systemd[1]: wg-quick@wg0.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit wg-quick@wg0.service has entered the 'failed' state with result 'exit-code'.
Apr 21 23:27:32 host systemd[1]: Failed to start WireGuard via wg-quick(8) for wg0.
-- Subject: A start job for unit wg-quick@wg0.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit wg-quick@wg0.service has finished with a failure.
--
-- The job identifier is 409 and the job result is failed.
```

**Comment by randomshell** [comment]
Github saves previous comments where you pasted your IP. You may want to delete them https://help.github.com/en/enterprise/2.19/user/github/building-a-strong-community/tracking-changes-in-a-comment

**Comment by angristan** [comment]
> Consult /var/lib/dkms/wireguard/1.0.20200413/build/make.log for more information.

Could we these?

**Comment by Archerious** [comment]
> 
> 
> > Consult /var/lib/dkms/wireguard/1.0.20200413/build/make.log for more information.
> 
> Could we see those?

It's showing as empty, let me try installing again.

**Comment by Archerious** [comment]
# ./wireguard-install.sh
IPv4 or IPv6 public address:  xxxxxxxxxxx
Public interface: ens3
WireGuard interface name: wg0
Server's WireGuard IPv4: 10.66.66.1
Server's WireGuard IPv6: fd42:42:42::1
Server's WireGuard port: 61941
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Get:3 http://deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:4 http://deb.debian.org/debian unstable InRelease [146 kB]
Get:5 http://deb.debian.org/debian unstable/main amd64 Packages.diff/Index [27.9                                kB]
Get:6 http://deb.debian.org/debian unstable/main Translation-en.diff/Index [27.9                                kB]
Get:7 http://deb.debian.org/debian unstable/main amd64 Packages 2020-04-22-0801.                               14.pdiff [10.5 kB]
Get:8 http://deb.debian.org/debian unstable/main amd64 Packages 2020-04-22-1402.                               51.pdiff [19.0 kB]
Get:9 http://deb.debian.org/debian unstable/main amd64 Packages 2020-04-22-2002.                               10.pdiff [18.5 kB]
Get:10 http://deb.debian.org/debian unstable/main amd64 Packages 2020-04-23-0201                               .18.pdiff [7322 B]
Get:10 http://deb.debian.org/debian unstable/main amd64 Packages 2020-04-23-0201                               .18.pdiff [7322 B]
Get:11 http://deb.debian.org/debian unstable/main Translation-en 2020-04-22-0801                               .14.pdiff [1740 B]
Get:12 http://deb.debian.org/debian unstable/main Translation-en 2020-04-22-2002                               .10.pdiff [3261 B]
Get:13 http://deb.debian.org/debian unstable/main Translation-en 2020-04-23-0201                               .18.pdiff [1065 B]
Get:13 http://deb.debian.org/debian unstable/main Translation-en 2020-04-23-0201                               .18.pdiff [1065 B]
Fetched 313 kB in 6s (51.5 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
3 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
linux-headers-4.19.0-8-amd64 is already the newest version (4.19.98-1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
iptables is already the newest version (1.8.2-4).
qrencode is already the newest version (4.0.2-1).
resolvconf is already the newest version (1.79).
The following additional packages will be installed:
  dkms linux-headers-amd64 wireguard-dkms wireguard-tools
Suggested packages:
  python3-apport menu
The following NEW packages will be installed:
  dkms linux-headers-amd64 wireguard wireguard-dkms wireguard-tools
0 upgraded, 5 newly installed, 0 to remove and 3 not upgraded.
Need to get 0 B/426 kB of archives.
After this operation, 2396 kB of additional disk space will be used.
Selecting previously unselected package dkms.
(Reading database ... 56095 files and directories currently installed.)
Preparing to unpack .../archives/dkms_2.6.1-4_all.deb ...
Unpacking dkms (2.6.1-4) ...
Selecting previously unselected package linux-headers-amd64.
Preparing to unpack .../linux-headers-amd64_4.19+105+deb10u3_amd64.deb ...
Unpacking linux-headers-amd64 (4.19+105+deb10u3) ...
Selecting previously unselected package wireguard-dkms.
Preparing to unpack .../wireguard-dkms_1.0.20200413-2_all.deb ...
Unpacking wireguard-dkms (1.0.20200413-2) ...
Selecting previously unselected package wireguard-tools.
Preparing to unpack .../wireguard-tools_1.0.20200319-1_amd64.deb ...
Unpacking wireguard-tools (1.0.20200319-1) ...
Selecting previously unselected package wireguard.
Preparing to unpack .../wireguard_1.0.20200319-1_all.deb ...
Unpacking wireguard (1.0.20200319-1) ...
Setting up linux-headers-amd64 (4.19+105+deb10u3) ...
Setting up dkms (2.6.1-4) ...
Setting up wireguard-dkms (1.0.20200413-2) ...
Loading new wireguard-1.0.20200413 DKMS files...
Building for 4.19.0-8-amd64
Building initial module for 4.19.0-8-amd64
Error! Bad return status for module build on kernel: 4.19.0-8-amd64 (x86_64)
Consult /var/lib/dkms/wireguard/1.0.20200413/build/make.log for more information                               .
dpkg: error processing package wireguard-dkms (--configure):
 installed wireguard-dkms package post-installation script subprocess returned e                               rror exit status 10
Setting up wireguard-tools (1.0.20200319-1) ...
dpkg: dependency problems prevent configuration of wireguard:
 wireguard depends on wireguard-dkms (>= 0.0.20200121-2) | wireguard-modules (>=                                0.0.20191219); however:
  Package wireguard-dkms is not configured yet.
  Package wireguard-modules is not installed.

dpkg: error processing package wireguard (--configure):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.8.5-2) ...
Errors were encountered while processing:
 wireguard-dkms
 wireguard
E: Sub-process /usr/bin/dpkg returned an error code (1)
* Applying /etc/sysctl.d/20-openvpn.conf ...
net.ipv4.ip_forward = 1
* Applying /etc/sysctl.d/99-sysctl.conf ...
* Applying /etc/sysctl.d/protect-links.conf ...
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
* Applying /etc/sysctl.d/wg.conf ...
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
* Applying /etc/sysctl.conf ...
Failed to start wg-quick@wg0.service: Unit wg-quick@wg0.service not found.
IPv4 Detected
Client's WireGuard IPv4 10.66.66.2
Client's WireGuard IPv6 fd42:42:42::2
First DNS resolver to use for the client: 1.1.1.1
Second DNS resolver to use for the client: 8.8.8.8
Job for wg-quick@wg0.service failed because the control process exited with erro                               r code.
See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.

Here is your client config file as a QR Code:

**Comment by Archerious** [comment]
> 
> 
> > Consult /var/lib/dkms/wireguard/1.0.20200413/build/make.log for more information.
> 
> Could we see those?

Hmm still same error:

```
# cat var/lib/dkms/wireguard/1.0.20200413/build/make.log
cat: var/lib/dkms/wireguard/1.0.20200413/build/make.log: No such file or directory
```

**Comment by angristan** [comment]
Can you try again after a `apt install bc`?

**Comment by Archerious** [comment]
That fixed it! :)

You're the best Angristan, thanks again for your hard work wireguard is fantastic, faster than openvpn.

**Comment by angristan** [comment]
I think it's a bug in the Debian packaging https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=956869
