### ISSUE TITLE
Deep Packet Inspection

### ISSUE THREAD

**Issue by digitaloceanvpsph** [angristan/wireguard-install#71]
Good day!
Hello Angristan and Contributors, 
Is wireguard capable to bypass deep packet inspection by srambles metadata to prevent DPI, vpb blocking and  throttling. 

I`m newbie at wireguard.

Thanks for the script. Appreciated.

**Comment by angristan** [comment]
No that I know of, Wireguard is not recommended for that use case (yet) 🙁

**Comment by digitaloceanvpsph** [comment]
Are you open to android app development about wireguard
drop a message to me ph.lawrence.xyz@gmail.com for more details thank you.
