### ISSUE TITLE
Raspberry Pi / Raspbian compatibility

### ISSUE THREAD

**Issue by angristan** [angristan/wireguard-install#73]
Related:

- #17 (docs)
- #56 (detect raspbian)
- #43 (resolvconf)

**Comment by randomshell** [comment]
Why do we install resolvconf anyway?

**Comment by angristan** [comment]
See https://github.com/angristan/wireguard-install/commit/721d16e97965c51a0b131b80ca2c40c5a8f40fad

**Comment by clach04** [comment]
Raspbian Debian 9 stretch support is available with https://github.com/pivpn/pivpn - at least it installs/builds. Not tried to connect yet :)

**Comment by clach04** [comment]
Just successfully tested with Android client to server setup with pivpn and Debian 9 with Raspbian, posted https://github.com/angristan/wireguard-install/pull/115

**Comment by cantalupo555** [comment]
> Just successfully tested with Android client to server setup with pivpn and Debian 9 with Raspbian, posted #115

Can i run this script on arm64 server?
