### ISSUE TITLE
App Store Connection Issue

### ISSUE THREAD

**Issue by OmanCoding** [angristan/wireguard-install#77]
Dear @angristan 

The installation works fine and easy. WG connection is also fast.

However I noticed that connection to the App Store from Mac or iPhone **is not working.**

Is there a configuration to be done?

Regards,
Nasser

<img width="420" alt="Screen Shot 2020-05-08 at 9 12 39 PM" src="https://user-images.githubusercontent.com/38236933/81430852-3a14e000-9171-11ea-8e1b-19e1e8539614.png">

**Comment by angristan** [comment]
That's weird, I'm using it with the macOS app too..

**Comment by angristan** [comment]
At which step does it happen?

**Comment by OmanCoding** [comment]
It happens when I open the App Store app, it doesn't show the listing of
apps and show connection error and retry button.

This happens in the iPhone too,

**Comment by OmanCoding** [comment]
I tried to close the VPN and opened the App Store app, then switched ON the
VPN and I clicked update on one of the apps, it did update. Kind of some
parts of the App Store domains are not connecting.

I am hosting on Linode Singapore.

**Comment by angristan** [comment]
Oh OK. Maybe try to change the DNS resolver? (`DNS = ...`)

**Comment by OmanCoding** [comment]
Hi @angristan,

I changed to AWS and it worked without issue.

Thanks for support.
