### ISSUE TITLE
Abort the script if OpenVZ or LXC

### ISSUE THREAD

**Issue by angristan** [angristan/wireguard-install#8]

**Comment by slrslr** [comment]
Hello @angristan , Your script failed to install WG on Debian 11 LXC container VPS saying "LXC is not supported (yet)." https://github.com/Nyr/wireguard-install script installed it apparently without issue. Can you please mirror part of their process in your script to make it working or temporarily link to their script (or other noob friendly way to setup it) so people does not face dead end? Thank you
