### ISSUE TITLE
Script broken if you previously installed Wireguard

### ISSUE THREAD

**Issue by allquixotic** [angristan/wireguard-install#80]
On Ubuntu 20.04, I installed wireguard with `apt install wireguard wireguard-tools wireguard-dkms` but didn't do _any_ configuration at all.

The wireguard-install script aborts without doing necessary setup when it detects packages installed, but then `add-client` always fails because my setup is invalid (for example, `/etc/wireguard/params` doesn't exist!)

Basically installing the software packages should not be equated with assuming the wireguard tunnel is configured.

**Comment by MostafaNaguib** [comment]
The installer script actually abort because it detects existence of '/etc/wireguard' if you remove it, it will probably continue installing/configuring

**Comment by angristan** [comment]
Indeed:

https://github.com/angristan/wireguard-install/blob/2e492d263ae35b6874831ea1bbc6025f150d9f9f/wireguard-install.sh#L92-L95

**Comment by allquixotic** [comment]
Thanks for explaining the check. However, this check is likely to produce false positives. On Ubuntu at least, just `apt install wireguard` will create that directory, but not put anything in it.

The check could determine if there are any _files_ within `/etc/wireguard` -- if there are, the existing behavior of echoing an error and aborting should occur, to avoid overwriting a user's manual config. If there are _no_ files in `/etc/wireguard`, you can safely assume that wireguard is not set up, and proceed with the script.

Either that, or you can read a "Y" or "N" from the command line using the `read` builtin to ask the user if they want to proceed anyway.

I think this is going to be a fairly common use case for your users of this script:

1. Install wireguard via the package manager.
2. Spend an hour trying to configure it
3. Realize it's more complicated and give up, then google for helper scripts.
4. Find this script and try to use it.

Also, the error message of the script is a bit misleading. It made me think "Oh, OK, so the install is done. That means I can add a client now, right?" -- _Wrong_! :) I needed to fix this issue so I could run the install script before using `add-client`.
