### ISSUE TITLE
dash at beginning of client config

### ISSUE THREAD

**Issue by chppppp** [angristan/wireguard-install#86]
what kind of monsters put a dash in the beginning of their file name?

```
root@WTF:~# cat '-client-8YXj7Lejv0.conf'
cat: invalid option -- 'c'
Try 'cat --help' for more information.
```

```
root@WTF:~# cat -client-8YXj7Lejv0.conf
cat: invalid option -- 'c'
Try 'cat --help' for more information.
```

**Comment by chppppp** [comment]
I know the solution to this is ` cat ./-client-8YXj7Lejv0.conf` but this is kinda mean to new users :P

**Comment by Andrei-Dr** [comment]
That's not the solution. The solution is double dash ;)
cat -- -client-8YXj7Lejv0.conf

**Comment by AndreiG6** [comment]
Solution is double dash ;)
cat -- -client-8YXj7Lejv0.conf

**Comment by chppppp** [comment]
double dash is new to me! many ways to skin a cat :D

**Comment by randomshell** [comment]
https://github.com/angristan/wireguard-install/blob/7c6da8df0ebf39f37beae5aa45898c4120d64041/wireguard-install.sh#L121-L122
https://github.com/angristan/wireguard-install/blob/7c6da8df0ebf39f37beae5aa45898c4120d64041/wireguard-install.sh#L48-L48

@chppppp you didn't specify an interface name, the file doesn't start with a dash.

We should add checks to avoid empty answers. If anyone wants to open a PR it's a good first issue.
