### ISSUE TITLE
ping:  sendmsg: Destination address required

### ISSUE THREAD

**Issue by RodneyBrown** [angristan/wireguard-install#87]
I've tried setting up wireguard manually and by using this script, on the server when I try to ping a valid client, I get:

`$ ping 10.66.66.2
PING 10.66.66.2 (10.66.66.2) 56(84) bytes of data.
From 10.66.66.1 icmp_seq=1 Destination Host Unreachable
ping: sendmsg: Destination address required
`
Currently running Kubuntu 20.04 on both server and client.  I had wireguard working on Ubuntu 19.10 and Pop_Os! 19.10 before installing Kubuntu on both machines.

**Comment by randomshell** [comment]
Hi @RodneyBrown 

Thanks for reporting this bug. The linked PR should fix it.
