### ISSUE TITLE
wrong permission after install

### ISSUE THREAD

**Issue by joks-arch** [angristan/wireguard-install#96]
Hello so when i run script 
./wireguard-install.sh
i have information that: You need to run this script as root

so i run script with sudo but after that client config was saved in /root directory not i /home and i can`t access to /etc/wireguard i must run chmod 755 after installation for /etc/wireguard and chmod 644 for files (wg0.conf and parms) and now i can go into /etc/wireguard and view or chagne settings in wg0.conf

i use your other script openvpn and there i dont have that issuse with client config file saved to /root directory and access to /etc/openvpn so i think this is little bug ?

**Comment by randomshell** [comment]
> client config was saved in /root directory not i /home

This should be changed. Thanks.

> i can`t access to /etc/wireguard i must run chmod 755 after installation

@angristan set it to 600 in 1981429774a9958df8254674a6eb4cad93c10a07. The configuration file `/etc/wireguard/wg0.conf` contains private keys so i think he is right to set it to `600`. If you do `ls -l /etc/openvpn` you see that the certificate and the key files have the same `600` permissions, the difference with wireguard is that the keys aren't separate files but are saved in the config. This means that you need to be root to view and change `wg0.conf`, it's not a bug.
